### ISSUE TITLE
Messages always have empty content field in them

### ISSUE THREAD

**Issue by yoraze** [discord-php/DiscordPHP#1002]
## Environment
- PHP Version:
    - 7.4.18
- DiscordPHP Version:
    - dev-master#4459c36 (or #d3fbf6e aka latest commit at the moment)

## Describe the bug

Messages always have empty content field in them.
Everything works fine if I use 7.3.3 instead of dev-master.
Dont know where and when the bug happened. (in repository I mean)

## To Reproduce
```php
$discord->on('message', function(Message $message) : void{
    var_dump($message->content); // Will be always string(0) ""
});
```

**Comment by SQKo** [comment]
https://github.com/discord-php/DiscordPHP/issues/905 ?

1.
```php
$discord = new Discord([
    'token' => ...,
    'intents' => Intents::getDefaultIntents() | Intents::MESSAGE_CONTENT,
]);
```

2. https://discord.com/developers/applications/ > Your Application > Bot > Privileged Gateway Intents > Message Content Intent
![gambar](https://user-images.githubusercontent.com/87897282/205442755-9b102909-e326-4353-afbb-e59bff5a2ed3.png)


> ## Environment
> 
>     * PHP Version:
>       
>       * 7.4.18
> 
>     * DiscordPHP Version:
>       
>       * dev-master#4459c36 (or #d3fbf6e aka latest commit at the moment)

dev-master will require PHP 8.0+

**Comment by yoraze** [comment]
Oh I see now
In #511 message intents disabled by default
Thanks!
