### ISSUE TITLE
Example for Choices

### ISSUE THREAD

**Issue by maoleng** [discord-php/DiscordPHP#1006]
Hello, I need an example code for create the interaction include choices like 
![image](https://user-images.githubusercontent.com/91431461/205528837-34b857d9-cecf-45f7-afd6-047039448b36.png)

**Comment by xWildFire** [comment]
```
$option = new Option($discord);
$option->setName('sub');
$option->setDescription('test');
$option->setType(Option::SUB_COMMAND);

$subOption = new Option($discord);
$subOption->setType(Option::STRING);
$subOption->setName('int');
$subOption->setDescription('suggest int');
$subOption->setRequired(true);
$subOption->addChoice(Choice::new($discord, 'one', '1'));
$subOption->addChoice(Choice::new($discord, 'two', '2'));
$subOption->addChoice(Choice::new($discord, 'second', '2'));
$option->addOption($subOption);

$cmdInstance = new Command($discord, [
	'name' => 'cmd',
	'description' => 'test',
	'options' => [$option]
]);
$discord->application->commands->save($cmdInstance);
```

**Comment by maoleng** [comment]
> ```
> $option = new Option($discord);
> $option->setName('sub');
> $option->setDescription('test');
> $option->setType(Option::SUB_COMMAND);
> 
> $subOption = new Option($discord);
> $subOption->setType(Option::STRING);
> $subOption->setName('int');
> $subOption->setDescription('suggest int');
> $subOption->setRequired(true);
> $subOption->addChoice(Choice::new($discord, 'one', '1'));
> $subOption->addChoice(Choice::new($discord, 'two', '2'));
> $subOption->addChoice(Choice::new($discord, 'second', '2'));
> $option->addOption($subOption);
> 
> $cmdInstance = new Command($discord, [
> 	'name' => 'cmd',
> 	'description' => 'test',
> 	'options' => [$option]
> ]);
> $discord->application->commands->save($cmdInstance);
> ```

Thank you!
