### ISSUE TITLE
Question about voice_states

### ISSUE THREAD

**Issue by JokerMisfits** [discord-php/DiscordPHP#1040]
Branch : dev-master

There is  * @property object[]|null $voice_states  Array of voice states.
In Guild.php  but in protected $fillable no line 'voice_states', 
and that's why it won't load.

Has this setting been moved or is it a bug?
Robo_N1X — Yesterday, at 14:00
seems has been removed, please issue a bug report to remove the phpdoc property

**Comment by SQKo** [comment]
Removed.

To be noted that `voice_states` are received from `GUILD_CREATE` events are stored as `$channel->members` in a voice state.
