### ISSUE TITLE
$message->reply to message in thread intermittently fails with 

### ISSUE THREAD

**Issue by pd-cm** [discord-php/DiscordPHP#1073]
Calling `$message->reply( 'xyz' );` in reply to a message in a thread fails with `'You can only send messages to text channels.'`, even though the thread is a text channel.

Removing these lines from `src/Discord/Parts/Channel/Channel.php` resolves the issue, but seems problematic to remove. The messages send successfully without the check.
```
if (! $this->isTextBased()) {
             return reject(new \RuntimeException('You can only send messages to text channels.'));
}
```
**Environment**
- PHP Version:
    - 8.2.0
- DiscordPHP Version:
    - dev-master @ 9c905aa

**To Reproduce**
Send two replies to a message in a thread.

**Expected behavior**
The replies should go through without an error.

**Comment by CommandString** [comment]
We're unable to replicate this issue on our side. Could you be more specific about how we can reproduce?

**Comment by key2peace** [comment]
update and try again
