### ISSUE TITLE
Message startThread not populating thread attribute

### ISSUE THREAD

**Issue by ellisonpatterson** [discord-php/DiscordPHP#1074]
**Environment**
- PHP Version:
    - 8.2.1
- DiscordPHP Version:
    - dev-master (9c905aa7fa4eb574668bb06e3d21b611fd5ab188)

**Describe the bug**
When creating a thread linked to a message, the `thread` attribute does not get updated.
As @SQKo said, it should update the `thread` attribute in the `THREAD_CREATE` event, but it seems to not be working.
I tried with `THREAD_CREATE` enabled and disabled in the DiscordPHP instance, with `$message->thread` being null in both scenarios.

**To Reproduce**
```
$channelId = '1051858424029249616';

$discord->getChannel($channelId)->sendMessage(
    \Discord\Builders\MessageBuilder::new()->setContent("Test")
)->then(function($message) {
    var_dump($message->thread?->id);

    return \React\Promise\all([
        \React\Promise\resolve($message),
        $message->startThread([
            'name' => 'Test Thread'
        ])
    ]);
})->then(function(array $promises) {
    var_dump($promises[0]->thread?->id);
    var_dump($promises[1]->id);
});
```

**Expected behavior**
The `thread` attribute for Message should have the newly-created thread as its value.

**Comment by SQKo** [comment]
I was mistaken, it's actually `MESSAGE_UPDATE` that are responsible to update its `thread` attribute. Discord API doesn't explain this specifically in their docs. So we do not have the code to handle this yet. Also the data received from event seems too partial where it only contains thread id and channel type.
