### ISSUE TITLE
discord bot crashes completely after trying to send message to forum channels

### ISSUE THREAD

**Issue by Jannik44** [discord-php/DiscordPHP#1088]
**Environment**
- PHP Version:
    - 8.1.2
- DiscordPHP Version:
    - 7.3

**Describe the bug**
I tried to send messages to normal channels, works as expected, when i send messages into a forum thread i get no message and the program crashes

**To Reproduce**
```<?php

include __DIR__ . '/vendor/autoload.php';

use Discord\Discord;
use Discord\Parts\Channel\Message;
use Discord\WebSockets\Intents;
use Discord\WebSockets\Event;

$discord = new Discord([
    'token' => 'redacted',
    'intents' => Intents::getDefaultIntents()
    //      | Intents::MESSAGE_CONTENT, // Note: MESSAGE_CONTENT is privileged, see https://dis.gd/mcfaq
]);

$discord->on('ready', function (Discord $discord) {
    echo "Bot is ready!", PHP_EOL;

    // Listen for messages.
    $discord->on(Event::MESSAGE_CREATE, function (Message $message, Discord $discord) {
        if ($message->author != "<@1095101543872725092>") {
            echo "{$message->author->username}: {$message->content}", PHP_EOL;
            
            $channel = $discord->getChannel($message->channel_id);
            if ($message->content == "e" or $message->content == "E")
                $channel->sendMessage('E');
        }
    });
});
$discord->run();
```

**Expected behavior**
it should send a message in the forum thread

**Screenshots**
![grafik](https://user-images.githubusercontent.com/76906033/231201597-f9db941d-ff24-4fac-b653-d48c7754c459.png)
![grafik](https://user-images.githubusercontent.com/76906033/231201804-b3092457-b304-4cd4-ac6b-134ec5c45d7c.png)

**Comment by Exanlv** [comment]
Celeste time woop woop

**Comment by SQKo** [comment]
`getChannel()` can be only used to get Channel, not Threads. This is not a bug.

If you wish to get the thread or channel where the message was sent, just use `$message->channel`
