### ISSUE TITLE
Unnecessary manage_roles flag in Channel.php

### ISSUE THREAD

**Issue by PakToPack** [discord-php/DiscordPHP#1115]
**Environment**
- PHP Version:
    - 8.2.5
- DiscordPHP Version:
    - v10.0.0

**Describe the bug**
In Channel.php there is a check, whether bot has `manage_roles` permission. But that is unnecessary, because the bot can do overwrites if it has manage_channels permission.

**To Reproduce**
```php
$game_channel->setPermissions($part, array_keys($allow_player), array_keys($deny_cp))->done(function () use ($part, &$added_players, $discord, $player) {
                                $added_players[] = $player['discord_id'];
                                $discord->logger->info((sprintf("Allowed to watch game channel for PLAYER %s", $part->displayname)));
                            },
```

**Expected behavior**
Add role/member to permission_overwrites

**Screenshots**
https://imgur.com/kJ78qCu

**Additional context**
Maybe I am mistaken. But official documentation for discord API does not require this permission. And it did work without this in V7

**Comment by SQKo** [comment]
I removed the exception code and it still don't work
```
[2023-05-06T16:20:22.421946+00:00] DiscordPHP.DEBUG: BUCKET putchannels/872531139275919423/permissions/:overwrite_id queued REQ PUT channels/872531139275919423/permissions/275546238290493440
[2023-05-06T16:20:22.945568+00:00] DiscordPHP.WARNING: REQ PUT channels/872531139275919423/permissions/275546238290493440 failed: Discord\Http\Exceptions\NoPermissionsException: Forbidden - {
    "message": "Missing Permissions",
    "code": 50013
}
```
Using same code as yours, and bot only has `manage_channel` permission in the channel
![gambar](https://user-images.githubusercontent.com/87897282/236635666-9e1b3c84-4bcc-4d41-81fc-5cd2944cf31d.png)


> **Additional context** Maybe I am mistaken. But official documentation for discord API does not require this permission. And it did work without this in V7

You are probably mistaken, the API says clearly it needs the `manage_roles` (aka manage permissions in the channel)

https://discord.com/developers/docs/resources/channel#edit-channel-permissions

![gambar](https://user-images.githubusercontent.com/87897282/236635796-bfc42829-d0a2-4e5d-8fc9-5697ed66a0c0.png)

**Comment by PakToPack** [comment]
Ok, understood. Closed :)
