### ISSUE TITLE
"Sending command" issue

### ISSUE THREAD

**Issue by CatAnonymous** [discord-php/DiscordPHP#1132]
The text "Sending command" was not disabled after the response was sent, is referReply() supported like python?

```
    $discord->listenCommand('test', function (Interaction $interaction) {
        $content = $interaction->data->options->offsetGet('text')->value;

        $interaction->respondWithMessage(MessageBuilder::new()->setContent('Your text: ' . $content));

    });
```

**Comment by key2peace** [comment]
$interaction->acknowledgeWithResponse(); should trigger the change from sending to thinking,
then instead of respondWithMessage, use updateFollowUpMessage
