### ISSUE TITLE
Breaking change in ReactPHP Promise package causing TypeError in Discord PHP bot

### ISSUE THREAD

**Issue by gregpriday** [discord-php/DiscordPHP#1148]
**Description:**
Upon updating my project dependencies, my Discord bot built with `team-reflex/discord-php` started throwing a TypeError. The error message suggests a returned value of `React\Promise\Promise` where an instance of `React\Promise\ExtendedPromiseInterface` was expected.

**Steps to Reproduce:**

1. Update project dependencies with `composer update`.
2. Run the Discord PHP bot.

**Expected behavior:**
The bot runs without throwing any TypeErrors.

**Actual behavior:**
The bot throws the following error:

```
Fatal error: Uncaught TypeError: Discord\Http\Drivers\React::runRequest(): Return value must be of type React\Promise\ExtendedPromiseInterface, React\Promise\Promise returned in /Users/gpriday/Projects/DiscordBotTest/vendor/discord-php/http/src/Discord/Drivers/React.php:62
Stack trace:
```

**Further Details:**
The `react/promise` dependency updated to version `v3.0.0`, which seems to be causing this issue. When I lock my project to use `react/promise` version `2.10.*`, the error is resolved and the bot operates as expected.

**Environment:**
- PHP version: 8.2
- `team-reflex/discord-php` version: v10.0.0-RC5
- `react/promise` version: v3.0.0 (issue arises), v2.10.* (issue resolved)
- I'm encountering the same issue on a fresh project with only `team-reflex/discord-php` @ RC5 is a dependency.

**Comment by key2peace** [comment]
yay, after 6 years... anyways, we updated the composer.json accordingly, feel free to update and thanks for reporting
