### ISSUE TITLE
Message reactions property not filled when fetching message, cannot be freshened

### ISSUE THREAD

**Issue by Jamesthe1** [discord-php/DiscordPHP#1176]
**Environment**
- PHP Version:
    - 8.2.6
- DiscordPHP Version:
    - 7.3.4

**Describe the bug**
Whenever a message is fetched, its reaction value does not contain anything but the repository exists. This repository also cannot be freshened.

**To Reproduce**
```php
$channel->messages->fetch ($msg_id)->then(function (Message $message) {
    echo count($message->reactions)."\n";
    // Prints 0; does not loop
    foreach ($message->reactions as $reaction) {
        echo 'Has reaction '.$reaction->emoji->name."\n";
    }
});
```
```php
$channel->messages->fetch ($msg_id)->then(function (Message $message) {
    // Exception: "this repository cannot be freshened"
    $message->reactions->freshen()->done(function (ReactionRepository $repo) {
        echo count($repo)."\n";
        foreach ($repo as $reaction) {
            echo 'Has reaction '.$reaction->emoji->name."\n";
        }
    });
});
```

**Expected behavior**
The foreach statement should print out the amount of reactions and the emoji names. Foreach has worked before on repositories.

The `freshen` call was an assumed attempt to get the reactions, as this is how other repositories, such as roles, retrieve missing data.

**Additional context**
The reason for the `then` statement is because of a `React\Async\await` call, which happens because I would like to remain within the bounds of rate limits.

**Comment by SQKo** [comment]
Your message cache is probably outdated, please set the fresh argument to `true` in the `$channel->messages->fetch($msg_id, true)`

It is not possible to do `$message->reactions->freshen()` because such endpoint does not exists (Discord does not provide a Get ALL reactions), the only endpoint that do this is to fetch the message directly from the API and not from the cache.

**Comment by Jamesthe1** [comment]
Now that I'm able to verify this, adding `true` to the fetch function has resolved my issue.

It's good to know this usage of `done()` as well; I'll have to go through my code to update this.
