### ISSUE TITLE
PHP 8.2

### ISSUE THREAD

**Issue by rsecor** [discord-php/DiscordPHP#1192]
**Environment**
- PHP Version:
    - 8.2.13
    - DiscordPHP Version:
    - x.x.x

**Describe the bug**
  Problem 1
    - team-reflex/discord-php[dev-fix-voice-client-handle-ws-switch, dev-legacy-cache-wrapper, dev-master, dev-subscriptions, dev-key2peace-patch-1, dev-valzargaming-patch-1, dev-promise-v3, dev-psr16-void-cache, v10.0.0-RC5, ..., v10.0.0-RC6] require discord-php/http ^10.1.7 -> satisfiable by discord-php/http[v10.1.7, ..., v10.3.0].
    - discord-php/http[v10.1.3, ..., v10.3.0] require react/http ^1.2 -> satisfiable by react/http[v1.2.0, ..., 1.x-dev].
    - team-reflex/discord-php[dev-develop, v5.1.0, ..., v5.2.0-RC3, v6.0.0-RC4, ..., v6.x-dev, v7.0.0-RC1, ..., v7.x-dev] require react/http ^1.1 -> satisfiable by react/http[v1.1.0, ..., 1.x-dev].
    - team-reflex/discord-php v1.0.0 requires php ^5.5.9 -> your php version (8.2.13) does not satisfy that requirement.
    - team-reflex/discord-php[v2.0.0, ..., v2.1.3, v3.0.0, ..., v3.2.4] require guzzlehttp/guzzle ~5.3|~6.0 -> found guzzlehttp/guzzle[5.3.0, ..., 5.3.x-dev, 6.0.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.2).
    - team-reflex/discord-php[v4.0.0, ..., v4.0.4] require php ^5.6|^7.0 -> your php version (8.2.13) does not satisfy that requirement.
    - team-reflex/discord-php[v5.0.0, ..., v5.0.3] require php ^7.0 -> your php version (8.2.13) does not satisfy that requirement.
    - team-reflex/discord-php[v5.0.10, ..., v5.0.12] require php ^7.2 -> your php version (8.2.13) does not satisfy that requirement.
    - team-reflex/discord-php[dev-cacheInterface, dev-patch-docs, v10.0.0-RC1, ..., v10.0.0-RC4] require psr/simple-cache ^1.0 -> found psr/simple-cache[1.0.0, 1.0.1] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - react/http[v1.2.0, ..., 1.x-dev] require psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires team-reflex/discord-php * -> satisfiable by team-reflex/discord-php[dev-fix-voice-client-handle-ws-switch, dev-legacy-cache-wrapper, dev-master, dev-subscriptions, dev-cacheInterface, dev-key2peace-patch-1, dev-valzargaming-patch-1, dev-develop, dev-patch-docs, dev-promise-v3, dev-psr16-void-cache, v1.0.0, v2.0.0, ..., v2.1.3, v3.0.0, ..., v3.2.4, v4.0.0, ..., v4.0.4, v5.0.0, ..., v5.2.0-RC3, v6.0.0-RC4, ..., v6.x-dev, v7.0.0-RC1, ..., v7.x-dev, v10.0.0-RC1, ..., v10.0.0-RC6, 9999999-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require team-reflex/discord-php:*" to figure out if any version is installable, or "composer require team-reflex/discord-php:^2.1" if you know which you need.

**To Reproduce**
composer require team-reflex/discord-php

**Expected behavior**
Library adds

**Comment by SQKo** [comment]
PHP 8.2 needs to use version 10 (RC available or dev-master)

besides, you have another dependency issue that is outside of this library, which is
>  - react/http[v1.2.0, ..., 1.x-dev] require psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
your lock file is fixed at psr/http-message 2.0 but the react/http only supports psr/http-message 1.x Try to downgrade that if your root project doesn't need it.

**Comment by 2colours** [comment]
Not sure about the exact point but I'm fine using v7 with latest PHP.
