### ISSUE TITLE
Ban function returning null

### ISSUE THREAD

**Issue by slicybt3w** [discord-php/DiscordPHP#1216]
php version: 8.1
discord-php version: 7.3

i keep getting this error when using ban()

`PHP Fatal error:  Uncaught Error: Call to a member function ban() on null in /home/slicybtw/NetBeansProjects/PhpProject2/index.php:90
Stack trace:
#0 [internal function]: {closure}()`

code 
```
$discord->registerCommand("ban", function(Message $message, $args) use ($discord) {

    try {
   if(count($args) < 1) {
       $message->channel->sendMessage("```Usage: @Together ban <@user or id> <reason>```");
   } else {
   
   $userId = str_replace(["<@",">","!"], '',$args[0]);
    
   $guildid = $message->channel->guild_id;
   
   $guild = $discord->guilds->get("id", $guildid);
   
   $member = $guild->members->get("id", $userId);
   
   $member->ban(0, implode(" ", array_slice(args, 1))) -> done(function (Ban $ban) {
       $message->channel->sendMessage("User <@{$userId}> has been banned");
   });
   
   
   }
   
   } catch (Exception $e) {
       $message->channel->sendMessage("An Error Occured: {$e->getMessage()}");
   }
 
});
```

even when i specify all the args

**Comment by SQKo** [comment]
You need to use `fetch(ID)` instead of `get()`, the `get()` may return `null` if the member is not cached, which is probably your case.

I've explained this in Discord replying your message. Please check the documentation and wiki for general references.

```php
$guild->members->fetch($userId)->then(function (Member $member) {
    return $member->ban(0, implode(" ", array_slice(args, 1))) ->then(function (Ban $ban) {
        return $message->channel->sendMessage("User <@{$userId}> has been banned");
    }, function ($exception) {
        // failed to ban or send message
    });
}, function ($exception) {
    // user id is not found in the server
})
->done();
```

**Comment by slicybt3w** [comment]
> You need to use `fetch(ID)` instead of `get()`, the `get()` may return `null` if the member is not cached, which is probably your case.
> 
> I've explained this in Discord replying your message. Please check the [documentation](http://discord-php.github.io/DiscordPHP/#repositories) and [wiki](https://github.com/discord-php/DiscordPHP/wiki/Member#get-a-specific-member) for general references.
> 
> ```
> $guild->members->fetch($userId)->then(function (Member $member) {
>     return $member->ban(0, implode(" ", array_slice(args, 1))) ->then(function (Ban $ban) {
>         $message->channel->sendMessage("User <@{$userId}> has been banned")->done();
>     }, function ($exception) {
>         // failed to ban
>     });
> }, function ($exception) {
>     // user id is not found in the server
> })
> ->done(); // with done() you can try catch this block of code further
> ```

i fetched it and first it logs this: `[2024-04-14T18:23:34.108632+03:00] DiscordPHP.DEBUG: BUCKET getguilds/1225096402665996381/members/:user_id queued REQ GET guilds/1225096402665996381/members/830395652659478619 [] []
[2024-04-14T18:23:35.102101+03:00] DiscordPHP.DEBUG: REQ GET guilds/1225096402665996381/members/830395652659478619 successful [] []
[2024-04-14T18:23:35.102160+03:00] DiscordPHP.DEBUG: http not checking {"waiting":0,"empty":true} []
`
nothing happens

**Comment by SQKo** [comment]
> i fetched it and first it logs this: `[2024-04-14T18:23:34.108632+03:00] DiscordPHP.DEBUG: BUCKET getguilds/1225096402665996381/members/:user_id queued REQ GET guilds/1225096402665996381/members/830395652659478619 [] [] [2024-04-14T18:23:35.102101+03:00] DiscordPHP.DEBUG: REQ GET guilds/1225096402665996381/members/830395652659478619 successful [] [] [2024-04-14T18:23:35.102160+03:00] DiscordPHP.DEBUG: http not checking {"waiting":0,"empty":true} [] ` nothing happens

That means the `$guild->members->fetch()` works, but the `$member->ban()` yet you have to handle the code inside `// failed to ban` because it does nothing by default if you leave it empty. Reasons why it fails might be due to your bot do not have permission to ban the server member.

**Comment by slicybt3w** [comment]
> > i fetched it and first it logs this: `[2024-04-14T18:23:34.108632+03:00] DiscordPHP.DEBUG: BUCKET getguilds/1225096402665996381/members/:user_id queued REQ GET guilds/1225096402665996381/members/830395652659478619 [] [] [2024-04-14T18:23:35.102101+03:00] DiscordPHP.DEBUG: REQ GET guilds/1225096402665996381/members/830395652659478619 successful [] [] [2024-04-14T18:23:35.102160+03:00] DiscordPHP.DEBUG: http not checking {"waiting":0,"empty":true} [] ` nothing happens
> 
> That means the `$guild->members->fetch()` works, but the `$member->ban()` yet you have to handle the code inside `// failed to ban` because it does nothing by default if you leave it empty. Reasons why it fails might be due to your bot do not have permission to ban the server member.

it has all the permissions
i made the exception but still nothing works
but whats this?
`DiscordPHP.DEBUG: http not checking {"waiting":0,"empty":true} []
`

**Comment by SQKo** [comment]
> > > i fetched it and first it logs this: `[2024-04-14T18:23:34.108632+03:00] DiscordPHP.DEBUG: BUCKET getguilds/1225096402665996381/members/:user_id queued REQ GET guilds/1225096402665996381/members/830395652659478619 [] [] [2024-04-14T18:23:35.102101+03:00] DiscordPHP.DEBUG: REQ GET guilds/1225096402665996381/members/830395652659478619 successful [] [] [2024-04-14T18:23:35.102160+03:00] DiscordPHP.DEBUG: http not checking {"waiting":0,"empty":true} [] ` nothing happens
> > 
> > 
> > That means the `$guild->members->fetch()` works, but the `$member->ban()` yet you have to handle the code inside `// failed to ban` because it does nothing by default if you leave it empty. Reasons why it fails might be due to your bot do not have permission to ban the server member.
> 
> it has all the permissions i made the exception but still nothing works but maybe this is the error? `DiscordPHP.DEBUG: http not checking {"waiting":0,"empty":true} [] `

No, another possible reason is that your promise `then()` is never called because you forgot to import `Member` namespace, causing internal ghost promise bug error.

**Comment by slicybt3w** [comment]
> > it has all the permissions i made the exception but still nothing works but maybe this is the error? `DiscordPHP.DEBUG: http not checking {"waiting":0,"empty":true} [] `
> 
> No, that's not an error. Another possible reason is that your promise `then()` is never called because you forgot to import `Member` namespace, causing internal ghost promise bug error.
> 
> If you don't want to handle exceptions then leave it null and use `done()` instead to always throw the exception back.

i checked documentation and there is Member namespace?

**Comment by SQKo** [comment]
> i checked documentation and there is Member namespace?

Yes, there is, As I've mentioned before, you need to make sure you imported the Member class, e.g.
`use Discord\Parts\User\Member;` on top of your code. Otherwise just remove all typehints. But be warned that would make troubleshooting code, especially calling methods such as `ban()` more difficult in future.

**Comment by slicybt3w** [comment]
> > i checked documentation and there is Member namespace?
> 
> Yes, there is, As I've mentioned before, you need to make sure you imported the Member class, e.g. `use Discord\Parts\User\Member;` on top of your code. Otherwise just remove all typehints. But be warned that would make troubleshooting code, especially calling methods such as `ban()` more difficult in future.

Brooo `use Discord\Parts\User\Member;` fixed it, thanks and sorry for wasting your time
