### ISSUE TITLE
getPermissions() undefined method error

### ISSUE THREAD

**Issue by slicybt3w** [discord-php/DiscordPHP#1217]
![Screenshot from 2024-04-15 18-46-23](https://github.com/discord-php/DiscordPHP/assets/80214266/558dc580-6039-42ef-bca4-25ab5f4013df)
PHP Discord: 7.3.5
PHP version: 8.1

i'm trying to get users permissions and use an if statement to see if the user has this permission or not
but i keep getting this error

Error:
`PHP Fatal error:  Uncaught Error: Call to undefined method Discord\Parts\Permissions\RolePermission::done() in /home/slicybtw/NetBeansProjects/PhpProject2/index.php:150
Stack trace:
#0 /home/slicybtw/NetBeansProjects/PhpProject2/vendor/react/promise/src/FulfilledPromise.php(28): {closure}()
#1 /home/slicybtw/NetBeansProjects/PhpProject2/index.php(153): React\Promise\FulfilledPromise->then()
#2 [internal function]: {closure}()`

Code:

`   $discord->registerCommand("check", function(Message $message) use ($discord) {
    try {
       $guildid = $message->channel->guild_id;
       $guild = $discord->guilds->get("id", $guildid);
       $guild->members->fetch($message->author->id) ->then( function (Member $member) {
                 $member->getPermissions()->done(function (RolePermission $permission, Message $message) {
                       if(!$permission == "ban_members") {
                           $message->channel->sendMessage("You Cant Use The Ban Command!");
                       }
        });
       })->done();
    } catch(Exception $e) {
        $message->channel->sendMessage($e->getMessage());
    }
});`

any help will be appreciated

**Comment by valzargaming** [comment]
It's usually best to check the documentation when calling a function you're not familiar with. [$member->getPermissions()](https://github.com/discord-php/DiscordPHP/blob/a8a617dcc6f55e15dc2ec43d97d7836d3fbaedca/src/Discord/Parts/User/Member.php#L411) does not return a function as your code seems to assume, but rather a either the expected role permission or null.

**Comment by valzargaming** [comment]
Closed due to no response, but known fix provided.
