### ISSUE TITLE
Rework direct message rate limits

### ISSUE THREAD

**Issue by kenygamer** [discord-php/DiscordPHP#467]
There's a new type of ratelimit called "bot quarantined". You hit this ratelimit after sending a few direct messages (it didn't exist before). Unlike traditional ratelimit, this "anti-spam" ratelimit bans your bot permanently unless you manually submit an appeal to Discord.

It's led me to lost many hours until I went to the Developer Center and saw that my bot was "quarantined". I had to create a new bot, but quickly after 29 or so direct messages the bot was banned again.

The exception is:

```
Forbidden
```

**Comment by davidcole1340** [comment]
Seems like nothing we can do and the solution isn't to send out many DMs:

![image](https://user-images.githubusercontent.com/991872/103160204-d0982d80-4836-11eb-97d3-fb9f19bc8995.png)
![image](https://user-images.githubusercontent.com/991872/103160206-d4c44b00-4836-11eb-8407-0f406361ab96.png)
![image](https://user-images.githubusercontent.com/991872/103160208-d988ff00-4836-11eb-98dc-7e4a90864be0.png)

**Comment by kenygamer** [comment]
@davidcole1340 This is what I mean. It's a real issue.

https://imgur.com/download/QpVFqhG/

I'm developing a bot for a large community so I need to open this much direct messages. I could send 800+ DMs before and now I can only send 25-40. And I don't know (if even) how long to wait to send the other handful of DMs.

**Comment by davidcole1340** [comment]
No one knows how many you can actually send, it seems like it's part of the anti-spam features. Discord won't tell us what the limit is. Best to talk to Discord to see if they can change anything (but I doubt they will budge).

**Comment by kenygamer** [comment]
@davidcole1340 I sent a long message to Discord requesting more information. But if my bot
cannot do this basic thing it's just unusable. And it's not only me.

**Comment by key2peace** [comment]
There is nothing WE can do about it, you got your ticket open with discord already, and they are the only ones being able to do something about it by either providing details on how it works, or changing the volumes allowed.

Summarized: this is not a library issue.

**Comment by kenygamer** [comment]
> There is nothing WE can do about it, you got your ticket open with discord already, and they are the only ones being able to do something about it by either providing details on how it works, or changing the volumes allowed.
> 
> Summarized: this is not a library issue.

The library can implement it which is why I opened the issue. If Discord doesn't tell me I will investigate myself.

**Comment by key2peace** [comment]
if we don't know WHAT exactly triggers the trap, then we cannot prevent it, so the only thing we COULD implement is detecting it triggering, at which point it is too late already. but hey, if you think you can do it, feel free to push a PR
