### ISSUE TITLE
How to check if an operation completed successfully?

### ISSUE THREAD

**Issue by sudofox** [discord-php/DiscordPHP#468]
E.g. Sending a DM to a user, sending a message to a channel, adding a reaction, and so on in such a way that the result can be used to determine the feedback sent to a user.

Right now I don't seem to have any way to verify that, say, a DM was sent successfully or to troubleshoot when it's not despite privacy settings. Same thing for when messages mysteriously don't get replied to.

I have tried ->then with a callback function but it never seems to gets triggered.

**Comment by davidcole1340** [comment]
The `->then()` should work, could you post some examples?

```php
$channel->sendMessage("hello, world!")->done(function (Message $message) {
    // action success
}, function ($e) {
    // action error
});
```

**Comment by kenygamer** [comment]
@sudofox You can use `->then()`, first is success callback, second is error callback.

**Comment by sudofox** [comment]
I'll give it a shot and let ya know.

**Comment by davidcole1340** [comment]
Did you get this working?

**Comment by sudofox** [comment]
Sorry, I was off from work since then til now, so I didn't get a chance to keep working on it. I'll be testing further soon, though. Thanks :D

**Comment by valzargaming** [comment]
@sudofox Did you get this working?

**Comment by sudofox** [comment]
Terrible sorry to never get back to this.

This doesn't work:

```
$channel->sendMessage("hello, world!")->done(function (Message $message) {
    // action success
}, function ($e) {
    // action error
});
```

However, if we remove the typing from the `$message` in the callback, it works.

This seems to be because nothing is actually passed into the success/failure function; trying to var_dump it or gettype on $message always returns NULL.

Because of this, it doesn't seem to be possible to use callbacks to perform additional actions such as replying to the user.

**Comment by sudofox** [comment]
In case it helps...

I did try something like this to try to perform an action, do some work, and then perform another action (e.g "Please wait"...."Here's your results:":

```php
echo "Received .react" . PHP_EOL;

$message->react("🐸")->then(function ($message) {
    // action success
    var_dump($message);
    echo "Success function" . PHP_EOL;
}, function ($e) {
    echo "Error function" . PHP_EOL;
});

echo "handleMessage done" . PHP_EOL;
```

However, the callback function does not get passed anything so I'm unable to do anything like additional processing/another reply.

```
Received .react
[02:14:13.581532] HTTPLogger.DEBUG: REQ PUT https://discord.com/api/v6/channels/<channel>/messages/<message>/reactions/%F0%9F%90%B8/@me queued  
handleMessage done
[02:14:13.694700] HTTPLogger.DEBUG: REQ PUT https://discord.com/api/v6/channels/<channel>/messages/<message>/reactions/%F0%9F%90%B8/@me successful  
[02:14:13.694797] HTTPLogger.INFO: BUCKET puthttps://discord.com/api/v6/channels/<channel>/messages/<message>/reactions/%F0%9F%90%B8/@me expecting rate limit, timer interval 250 ms  
NULL
Success function
```

If I try to typehint the callback function (e.g. `function (Message $message)` or `function (\Discord\Parts\Channel\Message $message)` then the callback doesn't execute at all, nor does it show any kind of error in stdout/stderr saying that something went wrong. That's why it took so long to work out why callbacks weren't executing.
