### ISSUE TITLE
Gateway closed

### ISSUE THREAD

**Issue by kenygamer** [discord-php/DiscordPHP#470]
I'm having a strange issue since today. Whenever I start my bot, I get a bunch of spam on the console with logs like:

```
Connection to tcp://162.159.136.232:443?hostname=discord.com failed:
Connection to tcp://162.159.128.233:443?hostname=discord.com failed:
Connection to tcp://162.159.137.232:443?hostname=discord.com failed:
Connection to tcp://162.159.136.232:443?hostname=discord.com failed:
Connection to tcp://162.159.136.232:443?hostname=discord.com failed:
Connection to tcp://162.159.137.232:443?hostname=discord.com failed:
Connection to tcp://162.159.135.232:443?hostname=discord.com failed:
Connection to tcp://162.159.135.232:443?hostname=discord.com failed:
Connection to tcp://162.159.135.232:443?hostname=discord.com failed:
Connection to tcp://162.159.128.233:443?hostname=discord.com failed:
```

To the point that there are so many logs that PHP warns of "too many files open" (sockets will mean).

**Comment by davidcole1340** [comment]
Usually a DNS problem, is this still happening? Can you try another DNS server?

**Comment by kenygamer** [comment]
> Usually a DNS problem, is this still happening? Can you try another DNS server?

@davidcole1340 It is still hapenning. How can I try another DNS?

**Comment by davidcole1340** [comment]
It usually takes the DNS from your computer, but I added an option on the lastest `master` to change it:
```php
$discord = new Discord([
    // ....
    'socket_options' => [
        'dns' => '8.8.8.8', // can change dns
    ],
]);
```

**Comment by kenygamer** [comment]
@davidcole1340 <details><summary>New rate limit</summary>I found that this issue happens when you try to add a bunch of roles.  I'm trying to add a role to 3,000 members and this issue happens. New ratelimit.</details>

**Comment by davidcole1340** [comment]
If it's the DNS issue it's not a Discord problem - it's with whatever DNS you are using. If you have tried a different DNS maybe it's a problem with your connection. You can try do the requests one after each other rather than all at once to slow it down:
```php
$role = ...;
$members = [...]; // array of member objects

$addRole = function () use ($members,  $role, &$addRole) {
    $member = array_shift($members);
    if ($member == null) return \React\Promise\resolve();
    $member->addRole($role)->done($addRole);
};
$addRole();
```

**Comment by kenygamer** [comment]
> If it's the DNS issue it's not a Discord problem - it's with whatever DNS you are using. If you have tried a different DNS maybe it's a problem with your connection. You can try do the requests one after each other rather than all at once to slow it down:
> 
> ```
> $role = ...;
> $members = [...]; // array of member objects
> 
> $addRole = function () use ($members,  $role, &$addRole) {
>     $member = array_shift($members);
>     if ($member == null) return \React\Promise\resolve();
>     $member->addRole($role)->done($addRole);
> };
> $addRole();
> ```

I already found out what causes this is when you try to add many roles.
I think the code you gave helps but it doesn't solve the root problem.

**Comment by kenygamer** [comment]
@valzargaming Still a bug. I don't know why it was labeled as a "question". 🙄 If you have a guild with 1,000+ users and you try to add a role to 1,000+ users in a row you might be able to reproduce this.

**Comment by key2peace** [comment]
it is not a dns issue, the first post clearly shows the ip of a discord gateway, this is just the way how reactphp establishes a https connection. I think your bot has been firewalled at that point for a while because of excessive connection attempts or other stuff which made it dislike you.

**Comment by kenygamer** [comment]
Close it for now. If it comes back, I just reopen ut.

**Comment by key2peace** [comment]
with pleasure
