### ISSUE TITLE
Warning: Warning: Array to string conversion in /storage/emulated/0/Download/projects/php_bot/vendor/team-reflex/discord-php/src/Discord/Repository/Guild/BanRepository.php on line 73

### ISSUE THREAD

**Issue by TheWhiteCube** [discord-php/DiscordPHP#477]
**Environment**
- PHP Version:
    - 8.0.0
- DiscordPHP Version:
    - 5.1.0

**Describe the bug**
The ban function does not work, warning ```Warning: Array to string conversion in /storage/emulated/0/Download/projects/php_bot/vendor/team-reflex/discord-php/src/Discord/Repository/Guild/BanRepository.php on line 73```

**To Reproduce**
```php
$message->channel->guild->bans->ban([
    'member' => $message->channel->guild->members['id']
    ]);
```

**Expected behavior**
warning, ban does not work

**Comment by davidcole1340** [comment]
The code you have provided is wrong which is why there is an error. Let me know what you are trying to do and I can help.

`$message->channel->guild->members` is an array of members, not a member object, so it makes sense that there is no `id` attribute. 

The `BanRepository::ban()` function doesn't take an array of options either.

**Comment by TheWhiteCube** [comment]
Hello, I tried to ban by ID, but it didn't work. Strangely, in this way I was successfully getting the member object this way.

**Comment by davidcole1340** [comment]
Who are you trying to ban? Someone tagged in the message?

**Comment by TheWhiteCube** [comment]
Yes, I get an ID from the message. Everything is correct with him, since the permission checks have been successfully passed.

**Comment by davidcole1340** [comment]
To ban a member you can simply do:
```php
$member->channel->guild->bans->ban($id)->done(function () {
    echo "Banned user\r\n";
});
```

Where `$id` is the ID of the member you want to ban. Note the `->done()` function call on the end - this causes any errors to show in console.

**Comment by TheWhiteCube** [comment]
Thank you. It's Working
