### ISSUE TITLE
Guild emojis won't load

### ISSUE THREAD

**Issue by kenygamer** [discord-php/DiscordPHP#479]
**Environment**
- PHP Version: 8.0.0
- DiscordPHP Version: 15e51a6

**Describe the bug**
I am trying to get the emoji list. I use the code that you can see below.

**To Reproduce**
```php
$guild = $this->getClient()->guilds->get("id", "764670711582949377");
foreach($guild->emojis->toArray() as $emoji){
	echo $emoji->name . ": " . $emoji->id . "\n";
}
```

**Expected behavior**
I should get a list of emojis, an `Emoji` array.

**Additional context**
Trying to use an emoji in an embed in the form `<Name:ID>` doesn't work either.

**Comment by key2peace** [comment]
you don't need toArray()

**Comment by davidcole1340** [comment]
They aren't automatically sent to the client so you have to fetch them:
```php
$guild->emojis->freshen()->done(function (EmojiRepository $emojis) {
    // loop
});
```
I'm going to add a method to first check if the repository is full, if it is return it, otherwise freshen it, similar to `fetch` but for the whole repository.
