### ISSUE TITLE
Message attributes are incomplete after bot restart

### ISSUE THREAD

**Issue by kenygamer** [discord-php/DiscordPHP#480]
**Environment**
- PHP Version: 8.0.0
- DiscordPHP Version: 71cc0c

**Describe the bug**
I opened an issue (#435) a month ago reporting a bug with `Channel::getMessageHistory()`. That's fixed, now, I have an unsolved bug. https://github.com/discord-php/DiscordPHP/issues/435#issuecomment-735242202

In fact, we started talking about the `Channel::getMessageHistory()` bug when that was another bug apart. Now I make a new issue since the initial bug was downplayed.

I fixed it using my own method. But I am obviously against this "method" and I am going with the most viable way.

**To put it simple: I open this issue to fix that `Message`s may have incomplete fields.**

`Event::MESSAGE_REACTION_ADD`'s event `Message` has a reaction property. And that reaction in turn has another property that is a `Mesage`. That message, if it was sent when the bot could catch it, will work perfectly and will have the properties `author` and `channel` defined. But if that message is sent before a restart you will see that the `Message` does not have the `author` or `channel` properties and you will have to fetch it with the `user_id` or `channel_id` which is what @davidcole1340  suggested to me (https://github.com/discord-php/DiscordPHP/issues/435#issuecomment-739061857)

**Solution**

1) Delete the `message` property. We can't have a `Message` with incomplete fields "sometimes".

2) Fetch the message before calling the event. It would not be instantaneous, but one of these should be chosen.

**To Reproduce**
```php
//before
$discord->on(Event::MESSAGE_REACTION_ADD, function(MessageReaction $reaction){
    echo $reaction->message->author->id . "\n"; //success
});
//after
$discord->on(Event::MESSAGE_REACTION_ADD, function(MessageReaction $reaction){
    echo $reaction->message->author->id . "\n"; //error
});
```

**Expected behavior**
`Message`s should have its `author` and `channel` set in the above case.

**Comment by valzargaming** [comment]
Understanding this issue requires an understanding of how the message repository works. There are two types of messages that DiscordPHP uses (even though they are not explicitly defined as such), those being raw and cached. To be able to cache messages the option to do so must be enabled.
```php
$discord = new Discord([
    'storeMessages' => true,
    ...
]);
```

The library does not fetch all messages from all channels when it connects, and in fact cannot do so as it will only be able to fetch so many messages from each channel (IIRC 100 messages max) and it is considered by Discord to be bad practice to do so. If you need to save a message ID for persistent usage you should save the message ID to a file/database and ->fetch it when you need it again.

My own bot has a system specifically for this purpose. If you want a working example, search "$gender_message_id" on https://github.com/VZGCoders/Palace-DiscordPHP/ to see the different places where I use it.

**Comment by kenygamer** [comment]
@valzargaming I completely get you as far as the functioning of the `Message` is concerned. The messages that are sent in that session will be cached while the others will be fetched. My issue is open because there is no specification of it, I was struggling all afternoon months ago when I first had this issue.

Instead of restoring it, there should be a way to do it for all events, because it can lead to confusion. For example, if the `Event::MESSAGE_REACTION_ADD->message` does not guarantee to be cached while `Event::MESSAGE_CREATE` does, that is ilogical.

We must remove that misleading property and keep `message_id`, to avoid confusion. Take the example of (DiscordJS](https://github.com/discordjs/discord.js/)

**Comment by key2peace** [comment]
No, we want to keep generating api traffic to a minimum, if you insist on retrieving the message upon MESSAGE_REACTION_ADD,, you can use `$message = $channel->messages->fetch($mesage_id);` which
if in memory, returns from there, otherwise fetches it from discord.

**Comment by davidcole1340** [comment]
Although I'd like to keep the library "lightweight" (no unnessacary HTTP requests) I do agree there should be an easy way to check if a part is complete.

I had a look at DiscordJS and they do something similar with the `partial` property: https://discordjs.guide/popular-topics/reactions.html#awaiting-reactions

I'm thinking of adding the `partial` property (not the `partials` in the constructor - we will always emit all events) and use like so:

```php
$discord->on(Event::MESSAGE_REACTION_ADD, function (MessageReaction $reaction) {
  if ($reaction->partial) {
    $reaction->fetch()->then(function () {
      // do something
    });
  }
});
```

Although this will get messy fast. Any other ideas?

**Comment by kenygamer** [comment]
Add an option, like `fetchAlReactions`. It will fetch all reactions before the event is emitted

And to address the so concerned bandwidth, add a `partial` property. I would add this because it won't break current implementations, not really because DiscordJS uses it.

> Although this will get messy fast. Any other ideas?

Because exactly it would bring a mess.

**Comment by davidcole1340** [comment]
Adding an option means that all reactions will be fetched, so I don't want to do that. I will add the fetch function and if it has already been fetched it will not fetch it again.

**Comment by kenygamer** [comment]
@davidcole1340 No, you're not getting me. I don't want to refer to "fetch" with getting all reactions from all messages. It would be nonsense if the messages are not cached. What I'm saying is, add a `fetchAllReactions` option to fetch all reactions when the event is emitted and, regardless of that, add the `->partial` property and the `MessageReaction->fetch()` method you are telling me about.

**Comment by davidcole1340** [comment]
Implemented on the latest `develop` commit: https://github.com/discord-php/DiscordPHP/commit/e180aa3bdd6fd48347069a86408093225f67fef2

You can call `$reaction->fetch()` and it will only fetch what it is missing (if anything, otherwise it resolves instantly).
You can check if a part is partial with `$reaction->isPartial()`, but this is not really nessacary, you can just always use `fetch()` if you require everything.
