### ISSUE TITLE
Exceeding the maximum field name length causes the bot to be blocked

### ISSUE THREAD

**Issue by kenygamer** [discord-php/DiscordPHP#483]
## Issue description
The title says it all.  If you exceed the field name length, your bot will be blocked. This block status is poorly tested, but from what I could test, it doesn't allow me to send new messages.

## Solution
DiscordPHP should put some kind of premature validation like using `Field->setName()`. With this said, ban the ability of setting properties directly, in the entire `Discord\Parts\Embed` namespace.

**Comment by valzargaming** [comment]
Why are you even using `$embed->Field->` in the first place? The helper functions like `$embed->addFieldValues` exist for a reason and has the exception handling you're looking for. This is a not a bug, just improper usage.

**Comment by kenygamer** [comment]
@valzargaming Friend, you have a tendency not to read well before answering. 

It is exactly as you just said. This is a bug because that improper usage is allowed. Why **can** you set properties manually in the first place?

> ban the ability of setting properties directly, in the entire Discord\Parts\Embed namespace.

**Comment by davidcole1340** [comment]
I'll add checks to the embed proeprties. There is no reason you would have been "blocked" by doing this. The only way you could have been "blocked" is by breaking the invalid request rate limit: https://discord.com/developers/docs/topics/rate-limits#invalid-request-limit

**Comment by kenygamer** [comment]
@davidcole1340 Friend,  I'm shocked how you contradict everything I say. Why don't you take the test?

## Code 
```php
/** @var $client \Discord\Discord */
$test = false;
$loop->addPeriodicTimer(3, function() use(&$test, &$client){
    $embed = new Embed();
    $embed->title= "DiscordPHP";
    $embed->description = "DiscordPHP";
    $field = $client->factory(Field::class);
    if(!$test){
        $test = true;
        $field->name = str_repeat("X", 4000);
    }else{
         $field->name = "Discord Test";
     }
     $field->value = "** **";
     $embed->addField($field);
     //send
});
```

## Explanation

The first time the message is sent (wrong)  a `Bad Request` error is returned, while the upcoming messages will not be sent.

**Comment by key2peace** [comment]
'friend', I am shocked, why don't you read the Ratelimit information on discord that says if your bot generates too many 403's, it will get punished?

**Comment by kenygamer** [comment]
@key2peace Isn't that exactly what I'm telling you. 🤷‍♂️

My bot is being punished. If my bot wasn't punished this issue wouldn't be really relevant because I could just use the `Embed->addFieldValues()` accessor. 

 @davidcole1340 talks about the [Request Limit](https://discord.com/developers/docs/topics/rate-limits) which is

> 10,000 per minutes

 verbatim from the Discord Docs to which you made suggestion. My bot is being blocked at the first request.

What do we bump into?

**Comment by key2peace** [comment]
maybe thats a question you should ask discord about.

**Comment by davidcole1340** [comment]
Try on the latest master branch, fixed a bug when a request throws an exception.
