### ISSUE TITLE
Cannot create an invite

### ISSUE THREAD

**Issue by kenygamer** [discord-php/DiscordPHP#489]
# Code to reproduce
```php
$channel->createInvite([
    "max_age" => 1,
    "max_uses" => 99999,
    "temporary" => false,
    "unique" => true 
])->done(function(\Discord\Parts\Guild\Invite $invite){	
    echo $invite->code;
}, function($e){
    var_dump($e);
});
```

**Comment by davidcole1340** [comment]
`max_uses` must be less than 100, if you want unlimited use `0`. I'll add an option validator but Discord doesn't have the ranges on their website. Also `max_age` is in seconds so it will expire after 1 second.

**Comment by kenygamer** [comment]
> `max_uses` must be less than 100, if you want unlimited use `0`. I'll add an option validator but Discord doesn't have the ranges on their website. Also `max_age` is in seconds so it will expire after 1 second.

Sorry not to include it. The error I get is `404 Not Found` so apparently there is a wrong endpoint listed.

**Comment by davidcole1340** [comment]
It worked when I tried with no 404, can you add an http logger and see the endpoint being called?
