### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by kenygamer** [discord-php/DiscordPHP#490]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to send multiple requests to a website. The target website blocks me, because I am accessing from the same IP, although I can connect with proxies.

**Describe the solution you'd like**
DiscordPHP should add proxy support for whatever reason you need to connect to the API behind a proxy.

**Describe alternatives you've considered**
I have considered doing the requests myself. Also, I have considered adding the proxy directly to `react/http-server`. However, both solutions are impractical.

**Comment by davidcole1340** [comment]
HTTP requests to other sites aren't really in the scope of this library, and there's no point of accessing Discord's API from behind a proxy because everything is per-account. If you need to use a proxy set it on your system

**Comment by key2peace** [comment]
iptables supports uid owner/program name based filters, ever considered using that in a PREROUTING table? pretty much the same way you setup transparent proxying in your network on your software based router
