### ISSUE TITLE
Private messages cannot be sent

### ISSUE THREAD

**Issue by JonathanN1203** [discord-php/DiscordPHP#496]
Hey, when I try to send a direct message with my bot, I get the message that "Discord \ Parts \ User \ Member :: sendMessage ()" is not defined. The entire error message:
`Jonathan N.: .jn
PHP Fatal error:  Uncaught Error: Call to undefined method Discord\Parts\User\Member::sendMessage() in /root/DC-Bot/bot2.php:29
Stack trace:
#0 /root/DC-Bot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): {closure}()
#1 /root/DC-Bot/vendor/team-reflex/discord-php/src/Discord/Discord.php(687): Discord\Discord->emit()
#2 /root/DC-Bot/vendor/react/promise/src/FulfilledPromise.php(42): Discord\Discord->Discord\{closure}()
#3 /root/DC-Bot/vendor/react/promise/src/Promise.php(66): React\Promise\FulfilledPromise->done()
#4 /root/DC-Bot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}()
#5 /root/DC-Bot/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle()
#6 /root/DC-Bot/vendor/react/promise/src/Deferred.php(36): React\Promise\Promise::React\Promise\{closure}()
#7 /root/DC-Bot/vendor/team-reflex/discord-php/src/Discord/WebSockets/Events/MessageCreate.php(37): React\Promise\Deferred->resolve()
#8 /root/DC-Bot/vendor/team-reflex/discord-php/src/Discord/Discord.php(708): Discord\WebSockets\Events\MessageCreate->handle()
#9 /root/DC-Bot/vendor/team-reflex/discord-php/src/Discord/Discord.php(595): Discord\Discord->handleDispatch()
#10 /root/DC-Bot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Discord\Discord->handleWsMessage()
#11 /root/DC-Bot/vendor/ratchet/pawl/src/WebSocket.php(72): Ratchet\Client\WebSocket->emit()
#12 /root/DC-Bot/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(248): Ratchet\Client\WebSocket->Ratchet\Client\{closure}()
#13 /root/DC-Bot/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(194): Ratchet\RFC6455\Messaging\MessageBuffer->processData()
#14 /root/DC-Bot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Ratchet\RFC6455\Messaging\MessageBuffer->onData()
#15 /root/DC-Bot/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit()
#16 /root/DC-Bot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}()
#17 /root/DC-Bot/vendor/react/stream/src/DuplexResourceStream.php(193): Evenement\EventEmitter->emit()
#18 /root/DC-Bot/vendor/react/event-loop/src/StreamSelectLoop.php(245): React\Stream\DuplexResourceStream->handleData()
#19 /root/DC-Bot/vendor/react/event-loop/src/StreamSelectLoop.php(212): React\EventLoop\StreamSelectLoop->waitForStreamActivity()
#20 /root/DC-Bot/vendor/team-reflex/discord-php/src/Discord/Discord.php(1356): React\EventLoop\StreamSelectLoop->run()
#21 /root/DC-Bot/bot2.php(36): Discord\Discord->run()
#22 {main}
  thrown in /root/DC-Bot/bot2.php on line 29
`
My code looks like this:
`<?php
include __DIR__.'/vendor/autoload.php';

use Discord\Discord;
use Discord\WebSockets\Intents;
use Discord\Parts\User\Activity;

try {
    $discord = new Discord([
        'token' => str_replace("\n", "", file_get_contents("./token.toke")),
        'loadAllMembers' => true,
    ]);
} catch (\Discord\Exceptions\IntentException $e) {
}
$discord->on('ready', function ($discord) {
    echo "Bot is ready!", PHP_EOL;
    $activity_list = ["sich Server an.", "das alles Läuft.", "zu."]; // all activities.
    $act  = $discord->factory(Activity::class, [
        'name' => $activity_list[ array_rand( $activity_list ) ],
        'type' => 3
        ]);
        $discord->updatePresence( $act, false, 'over the Palace' );
    $discord->on('message', function ($msg, $discord) {
        echo "{$msg->author->username}: {$msg->content}",PHP_EOL;
        $lowmsg = str_replace("\.", ";", strtolower($msg->content));
        if(strpos($lowmsg, '.jn') !== false)
        {
            $msg->channel->sendMessage('Hello, world!');
            $msg->author->sendMessage('Hello, world!')->done(function (Message $message) {
                echo "MessageSend",PHP_EOL;
            });
        }
    });
});

$discord->run();`

**Comment by key2peace** [comment]
add ``use Discord\Parts\User\Member;`` and remove the typecasting in the done()

**Comment by JonathanN1203** [comment]
unfortunately then comes the same error message

**Comment by key2peace** [comment]
if you wanna send him a private: $msg->author->**user->**sendMessage

**Comment by JonathanN1203** [comment]
what do you mean by the stars

**Comment by key2peace** [comment]
thats markup langyage to make it bold, just omit them

**Comment by JonathanN1203** [comment]
ah ok it works. Thank you for the quick help
