### ISSUE TITLE
Request timed out after 60s

### ISSUE THREAD

**Issue by kenygamer** [discord-php/DiscordPHP#498]
**Environment**
- PHP Version: 8.0.0
- DiscordPHP Version: d5a122d
    

**Describe the bug**
DiscordPHP's fragility is shocking. Today, I came across this issue:

```
Request timed out after 60 seconds
```

Which caused the bot to crash.

I have been having this problem since I partnered up with a community of 6,000 members. Nearly 6,000 messages are sent every 15 minutes, which with a ratelimits system bucket should be properly handled. However, it is not, and apparently, some requests are timing out and causing the bot to crash.

**To Reproduce**
```php
$loop->addPeriodicTimer(600, function() use($guild) : void{
    foreach($guild->channels as $channel){
        $channel->sendMessage("Test")->done(null, function(){
          //504 Service Unavailable
        });
     }
});
```

**Expected behavior**
DiscordPHP must be able to handle high load, my bot cannot crash because DiscordPHP is not able to handle Discord's ratelimits properly.

**Screenshots**

**Additional context**
Ubuntu 18.04.3 LTS running on a dedicated server.

**Comment by davidcole1340** [comment]
Why do you private message a whole guild, especially every 10 minutes, Discord has made it pretty clear that you shouldn't broadcast messages to users via DM.

**Comment by kenygamer** [comment]
> Why do you private message a whole guild, especially every 10 minutes, Discord has made it pretty clear that you shouldn't broadcast messages to users via DM.

I have updated my code. My issue was reproduced when sending messages to a channel.

**Comment by kenygamer** [comment]
I'm getting SSL handshake failed errors too, I think it's related to #488. Why was my issue closed? This needs an urgent fix.

**Comment by davidcole1340** [comment]
The HTTP client has been changed to only have 5 pending requests at once which should help slow it down. I haven't had anyone else mention SSL handshake errors and haven't been able to reproduce them, so can only say it's your connection causing these.

![Screenshot from 2021-02-28 13-59-22](https://user-images.githubusercontent.com/991872/109404706-7568ef80-79cd-11eb-9971-bc276687c23b.png)

**Comment by kenygamer** [comment]
Where can I download the hotfix? Also, is the ratelimit update coming anytime soon?

**Comment by davidcole1340** [comment]
It's on the `develop` branch at  the moment
