### ISSUE TITLE
#381 follow-up

### ISSUE THREAD

**Issue by kenygamer** [discord-php/DiscordPHP#499]
**Environment**
- PHP Version: 8.0.0
- DiscordPHP Version: d5a122d

**Describe the bug**
I was struck when yesterday I was trying to do things inside an `ExtendedPromiseInterface` callback and I ran into #381 again. b063fe9 fixed part of the problem, but not all.

**To Reproduce**
```php
$channel->guild->channels->save($channel)->done(function($channel){
    echo PHP_EOL2;
});
```

**Expected behavior**
When trying to use an invalid constant, there is no error like `Warning: Use of undefined constant`

**Comment by davidcole1340** [comment]
Nothing we can do until promise v3 is released. Use the following in the meantime:

```php
$channel->guild->channels->save($channel)
->then(function($channel){
    // any processing
    echo PHP_EOL2;
})
->done(null, function (\Throwable $e) {
    echo "Exception: ".$e->getTraceAsString().PHP_EOL;
});
```

**Comment by kenygamer** [comment]
> Nothing we can do until promise v3 is released. Use the following in the meantime:
> 
> ```
> $channel->guild->channels->save($channel)
> ->then(function($channel){
>     // any processing
>     echo PHP_EOL2;
> })
> ->done(null, function (\Throwable $e) {
>     echo "Exception: ".$e->getTraceAsString().PHP_EOL;
> });
> ```

Ok, thanks.
