### ISSUE TITLE
Member object is missing the pending flag?

### ISSUE THREAD

**Issue by valzargaming** [discord-php/DiscordPHP#500]
This seems to be a new flag that was added only recently with the addition of Membership Screening. DPHP currently does not have any checks for this, nor does it appear to show up in the member objects.

Documentation:
[https://discord.com/developers/docs/topics/gateway#guild-member-update-guild-member-update-event-fields](https://discord.com/developers/docs/topics/gateway#guild-member-update-guild-member-update-event-fields)

**Comment by davidcole1340** [comment]
Discord is refactoring the membership screening process so I won't implement this until after.
