### ISSUE TITLE
PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback

### ISSUE THREAD

**Issue by fagidutt** [discord-php/DiscordPHP#506]
php[108715]: PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, class 'Discord\Parts\User\Client' does not have a method 'getHttp' in /var/www/bg/lib/vendor/team-reflex/discord-php/src/Discord/Discord.php on line 1521

hey there, maybe it's a common failure from my side (in which case i would really, really appreciate some hint), or it is something that changed (i use php 7.4 for the cli which runs the script)

the problem starts with my discordapi.php-file, and is triggered by the $client->linkDiscord()-function.

this is the region in the file that triggers the error: 
`$discord->on('ready', function (Discord $discord) {
    // DiscordPHP is ready
});
**$client->linkDiscord($discord, false);** // false signifies that we still want to use the HTTP server - default is true, which will use gateway
// register a command `/hello`
$client->registerCommand('hello', function (Interaction $interaction, Choices $choices) {`

php trace as given above:
`php[108715]: PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, class 'Discord\Parts\User\Client' does not have a method 'getHttp' in /var/www/bg/lib/vendor/team-reflex/discord-php/src/Discord/Discord.php on line 1521`
(when i ran the script in PHP8, this warning was a (fatal) error. as far as i can remember i was unable to run the script whatsoever because of this error.

maybe i'm completely wrong to post this here, but i was hoping for some help.

**Comment by davidcole1340** [comment]
Could you show your `composer.json` file? You are probably using the wrong version of DiscordPHP.

DiscordPHP-Slash requires DiscordPHP `dev-develop` at the moment.

**Comment by fagidutt** [comment]
sure. its below there.

`cat composer.json
{
    "require": {
        "discord-php/slash": "^1.0",
        "kambo/httpmessage": "^0.9.1",
        "team-reflex/discord-php": "^5.1",
        "discord-php/http": "^8.0",
        "laminas/laminas-httphandlerrunner": "^1.3",
        "amphp/amp": "^2.5",
        "symplely/spawn": "^1.1",
        "guzzlehttp/guzzle": "^7.2"
    }
}
`
i tried to add "minimum-stability": "dev", to composer.json, but it still wont load the correct dependencies for dev-develop :/

**Comment by davidcole1340** [comment]
You'll have to remove the `"team-reflex/discord-php": "^5.1",` as `discord-php/slash` requires a higher version. You shouldn't have to change too much (if any).

**Comment by fagidutt** [comment]
you are my hero of the day (and the day is young)!! :)
thanks for the quick assistance, in fact this also fixed my issues receiving the member-object from the api! before it used to be NULL, now it works :)

**Comment by davidcole1340** [comment]
Sweet as
