### ISSUE TITLE
Adding "use Discord\Discord;" at line 11 in DiscordPHP/docs/src/pages/api/01_basics.md 

### ISSUE THREAD

**Issue by Benjamin-Loison** [discord-php/DiscordPHP#514]
Hello,

I am frustrated when I follow the documentation (and haven't been coding in PhP for a while) and write like in http://discord-php.github.io/DiscordPHP/#basics: 
<?php
    include __DIR__.'/vendor/autoload.php';

    $discord = new Discord([
        'token' => 'Your-Token-Here',
    ]);
?>

and get "PHP Fatal error:  Uncaught Error: Class 'Discord' not found"

Adding "use Discord\Discord;" at line 11 in DiscordPHP/docs/src/pages/api/01_basics.md would solve people have my issue.
I can understand that it isn't a specific feature of your framework but it is specified in your basic example in README.md but not there.

Thank you

**Comment by davidcole1340** [comment]
I've added this, as well as adding a FAQ and development environment section. If you don't want to worry about imports you should look into the PHP Intelephense language server :)
