### ISSUE TITLE
Add slash command?

### ISSUE THREAD

**Issue by nathnat** [discord-php/DiscordPHP#516]
Hello world!
I just see this morning that Discord implement a new feature for bots called `slash command`
See : [https://discord.com/developers/docs/interactions/slash-commands](url)

I was wondering will you implement this ? Are you working on it ?
This could be a very good feature!

I'm working on my side on a litlle pull request where i will try to implement it.

Thanks for the response!

**Comment by oliverschloebe** [comment]
@davidcole1340 has you covered. Check out https://github.com/discord-php/DiscordPHP-Slash

**Comment by davidcole1340** [comment]
As Oliver said above there's a seperate package which plugs into DiscordPHP if you want. It is far from finished as slash commands have recently been refactored but it does work.

**Comment by nathnat** [comment]
Well, thanks that's very good! But maybe it will be better to add this in this awesome component?

**Comment by davidcole1340** [comment]
Slash commands and bots are two fundamentally different things and can operate independently of each other, so they have been split into two different packages. There are examples on the slash command repository for how to use the together, however.
