### ISSUE TITLE
joinVoiceChannel refers to removed options

### ISSUE THREAD

**Issue by hemberger** [discord-php/DiscordPHP#519]
**Environment**
- DiscordPHP Version:
    - 6.0.0

**Describe the bug**
The `joinVoiceChannel` function still uses options that have been removed in v6.0.0.
https://github.com/discord-php/DiscordPHP/blob/8e91539ea81367d53f491209a2546d0587483e04/src/Discord/Discord.php#L1167-L1172

I would submit a PR removing them, but I'm not exactly sure how you want to fix this. Use `$this->logger` if the passed in logger is `null` instead? Create a new logger with default settings just for the voice client?

Thanks!

**Comment by davidcole1340** [comment]
Not sure how I missed this, thanks. Will fix tomorrow.

If you'd like to submit a PR before I will probably let the voice client use the same logger as the `Discord` client, since there's no reason to have multiple loggers.
