### ISSUE TITLE
can not send message on channel that fetched from Guild

### ISSUE THREAD

**Issue by weichenlin** [discord-php/DiscordPHP#522]
**Environment**
- PHP Version:
    - 7.4.1
- DiscordPHP Version:
    - 6.0.0

**Describe the bug**
when I get channel by `$guild->channels->fetch()`
the `$channel->sendMessage()` silent fails

**To Reproduce**
```php
// this success
$discord->getChannel($myChannelId)->sendMessage("from getChannel");

$discord->guilds->fetch($myGuildId, true)->done(function (Guild $guild) use ($myChannelId, $discord) {
    $guild->channels->fetch($myChannelId, true)->done(function (Channel $ch) use ($discord) {
        echo "got channel\n"; // this line has executed
        // this fails
        $ch->sendMessage('from fetch channelId');
    });
});
```

**Expected behavior**
should see both message on discord channel

**Additional context**
use xdebug to trace code, an exception are thrown on Channel.php line 708:
`$botperms = $this->guild->members->offsetGet($this->discord->id)->getPermissions($this);`
the exception is : Call to a member function getPermissions() on null

**Comment by key2peace** [comment]
try ...->sendMessage("your message here")->then(null, function($response) { dump($response });

**Comment by weichenlin** [comment]
this's my config
```php
$discord = new Discord([
    'token' => $myToken,
    'intents' => Intents::getDefaultIntents() | Intents::GUILD_MEMBERS,
    'loadAllMembers' => true,
]);
```
in discord developer portal, bot page:
![Screenshot_20210422_010031](https://user-images.githubusercontent.com/3406567/115592735-2de44d00-a306-11eb-97fc-30f6f61c88e1.png)

I changed code to
```php
$guild->channels->fetch($myChannelId, true)->done(function (Channel $ch) {
    echo "got channel\n";
    $ch->sendMessage('from fetch channelId')->then(null, function($response) { var_dump($response); });
    echo "done\n";
});
```
and got:
```
[2021-04-21T17:02:58.884986+00:00] DiscordPHP.DEBUG: REQ GET channels/767679967327682581 successful [] []
got channel
[2021-04-21T17:03:38.658914+00:00] DiscordPHP.DEBUG: sending heartbeat {"seq":4} []
```
the var_dump and the msg "done" are not appear

**Comment by sherwomeister** [comment]
Why was the fix removed? Faced exactly the same problem, fixed it as in the commit:
```php
// src/Discord/Parts/Channel/Channel.php
// public function sendMessage($message, bool $tts = false, $embed = null, $allowed_mentions = null, ?Message $replyTo = null): ExtendedPromiseInterface

if (! $this->is_private && $member = $this->guild->members->offsetGet($this->discord->id)) {
            $botperms = $member->getBotPermissions();
// ...
```

**Comment by SQKo** [comment]
> Why was the fix removed? Faced exactly the same problem, fixed it as in the commit:
> 
> ```
> // src/Discord/Parts/Channel/Channel.php
> // public function sendMessage($message, bool $tts = false, $embed = null, $allowed_mentions = null, ?Message $replyTo = null): ExtendedPromiseInterface
> 
> if (! $this->is_private && $member = $this->guild->members->offsetGet($this->discord->id)) {
>             $botperms = $member->getBotPermissions();
> // ...
> ```

Sorry, the fix was simplified but overlooked, it was never removed. It is another new bug. It will be fixed soon, thanks for reporting!
