### ISSUE TITLE
can't sendMessage

### ISSUE THREAD

**Issue by zkjiaaa** [discord-php/DiscordPHP#531]
- PHP Version:
    - PHP 7.3.4 (cli) (built: Apr  2 2019 21:57:22) ( NTS MSVC15 (Visual C++ 2017) x64 )
      Copyright (c) 1997-2018 The PHP Group
      Zend Engine v3.3.4, Copyright (c) 1998-2018 Zend Technologies

- DiscordPHP Version:
    - v5.1.3

**Describe the bug**
I can get a message, but I can't send it.

**code**
```php
<?php

require __DIR__ . '/../vendor/autoload.php';

use Discord\Discord;
use Discord\WebSockets\Event;
use Discord\Parts\Channel\Message;

try {
    $discord = new Discord([
         //I'm sure my token is true
        'token' => 'my-token',
    ]);
} catch (\Discord\Exceptions\IntentException $e) {
}

$discord->on('ready', function ($discord) {
    echo "Bot is ready!", PHP_EOL;

    $discord->on('heartbeat', function () use ($discord) {
        echo "heartbeat called at: " . time() . PHP_EOL;
    });


    $discord->on(Event::MESSAGE_CREATE, function (Message $message) {
        // Hello <@member_id>!
        echo "{$message->author->username}: {$message->content}",PHP_EOL;
        $message->channel->sendMessage('Hello '.$message->author.'!');
    });
});

$discord->run();
```

**Screenshots**
I can get a message, but I can't send it. And no exception is thrown
![image](https://user-images.githubusercontent.com/28976643/118958339-ea780f80-b993-11eb-9c98-44829fd6c984.png)

**Comment by key2peace** [comment]
get a new token please and never submit it on a public page again, also please update DiscordPHP to the latest master version, your version is too old, then try again

**Comment by zkjiaaa** [comment]
> get a new token please and never submit it on a public page again, also please update DiscordPHP to the latest master version, your version is too old, then try again

ahhh, thank, ok. i  update DiscordPHP now.

**Comment by zkjiaaa** [comment]
it work.

step 1：

> update DiscordPHP version

step 2:

> `traceroute discord.com`

> i get ip : 162.159.138.233

> now traceroute that ip, change the 233 to 231

Finish.

PS: thank everyone help;
