### ISSUE TITLE
Channel is_private not working correctly

### ISSUE THREAD

**Issue by MohsinEngineer** [discord-php/DiscordPHP#540]
**Environment**
- PHP Version:
    - 7.3.24
- DiscordPHP Version:
    - 5.1.3

**Describe the bug**
`is_private` attribute returns `NULL` when the message is in fact a private message. Meanwhile returns `False` when message is sent in a public channel. 

**To Reproduce**
```php
$discord->on('message', function (Message $message, Discord $discord) use ($browser) {
    var_dump($discord->getChannel($message->channel_id)->is_private);
});
```

Then try sending a message from a DM and then from a known public channel.

**Expected behavior**
It should return `TRUE / FALSE` like a proper boolean.

**Additional feature request**
I'm not aware of any other method to check whether the message I'm receiving is DM or not. It shouldn't be this complicated where we have to:

- Fetch `channel_id` from `Message` object.
- Fetch `Channel` object using `Discord` object.
- Check `is_private` attribute of the channel.

A better way to do it would be to pass the `Channel` object inside the `Message` object instead of passing just the `channel_id`.

**Screenshots**

When sending the message in a *PUBLIC CHANNEL*:

![image](https://user-images.githubusercontent.com/19812560/119346305-7bf8c180-bcb3-11eb-9124-ca04b5a9bebd.png)
![image](https://user-images.githubusercontent.com/19812560/119346307-7bf8c180-bcb3-11eb-8e82-ab54c55b6a52.png)
![image](https://user-images.githubusercontent.com/19812560/119346306-7bf8c180-bcb3-11eb-8d79-372900ef38fd.png)

When sending a *DIRECT MESSAGE TO THE BOT*:

![image](https://user-images.githubusercontent.com/19812560/119346597-d98d0e00-bcb3-11eb-932c-016af02efbf9.png)
![image](https://user-images.githubusercontent.com/19812560/119346598-d98d0e00-bcb3-11eb-8d90-1a4225594ffd.png)

**Comment by key2peace** [comment]
I think you are misunderstanding is_private here, the 'private channel' flag you show in your screenshot is simply a tool to help you securing your channel, and is_private in discord php means, is this a DM (direct message) channel or not (better way would be to check if there is a guild_id attached to the message or not, as DM does not happen in a guild)

**Comment by MohsinEngineer** [comment]
`a tool to help you securing your channel` - can you please elaborate?

Keeping that in mind, I really think `is_private` should match the Discord definition for it. We can use a different key such as `is_secure` for determining whatever purpose it is currently serving.

Sorry if I'm confusing things still

**Comment by davidcole1340** [comment]
Instead of `$discord->getChannel($message->channel_id)->is_private` you can simply use `$message->channel->is_private`.

The code will be failing as the `getChannel` function returns null, as the private message channel does not exist in the cache, but when you call `$message->channel` it creates the channel if it does not exist. This has been changed in the latest version of DiscordPHP (but you'd have to upgrade PHP to use that).

And yes, you are correct in the interpretation of the `is_private` field, if it is a direct message channel it will return true and if it is anything else it will be false.
