### ISSUE TITLE
Error TLS handshake

### ISSUE THREAD

**Issue by thyagomuris** [discord-php/DiscordPHP#541]
I am getting this error several times during the day and I have already checked the PHP certificate and settings and it seems to me that everything is fine. Does anyone have any idea what it could be?

REQ POST https://discord.com/api/v6/channels/840967376387964958/messages failed: Connection to discord.com:443 failed during TLS handshake: Connection lost during TLS handshake

**Comment by key2peace** [comment]
the fact that this request is made using v6, and the current release uses v8, makes me suggest you to update, also, if you are using windows, see https://github.com/discord-php/DiscordPHP#windows-and-ssl

**Comment by thyagomuris** [comment]
Thanks @key2peace, 

A question that may seem stupid but is because I don't really know where to find it.

Do you have any documentation explaining how to migrate to V8?
