### ISSUE TITLE
Missing channel updatable attributes

### ISSUE THREAD

**Issue by JaxkDev** [discord-php/DiscordPHP#555]
**Environment**
- PHP Version:
    - 8.0.7
- DiscordPHP Version:
    - 6.0.1

**Describe the bug**
Unable to update the following channel attributes:
- nsfw (text/news/store channel)
- rate_limit_per_user (text channel)
- bitrate (voice channel)
- user_limit (voice channel)
- permission_overwrites

See https://discord.com/developers/docs/resources/channel#modify-channel for all possible updatable attributes.

**To Reproduce**
Steps to reproduce the behaviour:
- Create channel with any attributes, eg nsfw to true.
- Save said channel.
- Change an attribute listed above, eg nsfw to false.
- Save said channel.

**Expected behaviour**
Channel to be no longer nsfw.

**Actual behaviour**
Channel remains a nsfw channel.

**Screenshots**
N/A

**Additional context**
Issue requested on github from @davidcole1340 via discord.

**Comment by davidcole1340** [comment]
See above commit, you should use the overwrites repository to update permission overwrites.

**Comment by davidcole1340** [comment]
I pushed an update to a seperate branch - `bulk_update_overwrites` - can you give it a go with that and see how it works for you? I haven't tested it but should work. Change version to `dev-bulk_update_overwrites` in `composer.json` then run `composer update`.

**Comment by JaxkDev** [comment]
Branch works, thanks for the implementation appreciate it.
