### ISSUE TITLE
Components

### ISSUE THREAD

**Issue by K4zBeK** [discord-php/DiscordPHP#558]
Please add components support

**Comment by davidcole1340** [comment]
Already implemented on the [`feature/interactions`](https://github.com/discord-php/DiscordPHP/tree/feature/interactions) branch (waiting for testing). You can try it out by changing DiscordPHP's version to `dev-feature/interactions` inside your `composer.json` file and running `composer update`.

**Comment by K4zBeK** [comment]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires team-reflex/discord-php dev-feature/interactions, found team-reflex/discord-php[dev-master, dev-develop, v1.0.0, v2.0.0, ..., v2.1.3, v3.0.0, ..., v3.2.4, v4.0.0, ..., v4.0.4, v5.0.0, ..., v5.2.0-RC3, v6.0.0-RC4, v6.0.0, v6.0.1] but it does not match the constraint.

**Comment by davidcole1340** [comment]
The branch was merged into `develop` a couple weeks ago. Change the version to `dev-develop`.
