### ISSUE TITLE
Activity Buttons

### ISSUE THREAD

**Issue by JaxkDev** [discord-php/DiscordPHP#561]
**Is your feature request related to a problem? Please describe.**
No, just missing data.

**Describe the solution you'd like**
Button labels to be added to the Activity model.

**Describe alternatives you've considered**
N/A

**Additional context**
https://github.com/discord/discord-api-docs/blob/master/docs/topics/Gateway.md#activity-buttons

**Comment by davidcole1340** [comment]
Added, not parsed tho since there's limited things you can do with the `Activity` object in a bots case.
