### ISSUE TITLE
Allow emoji string in setEmoji method [develop v7.0.0-rc0]

### ISSUE THREAD

**Issue by SQKo** [discord-php/DiscordPHP#564]
`setEmoji` in both [Button](https://github.com/discord-php/DiscordPHP/blob/7a0848386ea236fab256110c011c8eb3aa43f363/src/Discord/Builders/Components/Button.php#L178) and [Option](https://github.com/discord-php/DiscordPHP/blob/7a0848386ea236fab256110c011c8eb3aa43f363/src/Discord/Builders/Components/Option.php#L114) argument should allow emoji string:

- Unicode: `setEmoji('❤️')`
- Custom Emoji: `setEmoji(':mmLol:216154654256398347')`
- Animated Emoji: `setEmoji('a:b1nzy:392938283556143104')`

**Comment by davidcole1340** [comment]
Can you try on the latest develop and let me know if it works for you.

**Comment by SQKo** [comment]
Yup, works for me on PHP 7.4 Windows. Thank you.
