### ISSUE TITLE
"GUILD_MEMBER_ADD" event does not fire

### ISSUE THREAD

**Issue by Jarode01** [discord-php/DiscordPHP#565]
Hi,

**Issue**
Event "GUILD_MEMBER_ADD" fire on my local server, but doesn't fire on production server.

**Environment**
- PHP Version:
    - 7.4.19 (prod server) 
- DiscordPHP Version:
    -  ??? (unable to find it)
- Composer Version :
    - 1.8.4 (prod server)
- Miscealaneous
    - Prod server is a cPanel shared based hosting

**My script**
```php
include __DIR__.'/vendor/autoload.php';

use Discord\Discord;
use Discord\WebSockets\Intents;
use Discord\WebSockets\Event;

$discord = new Discord([
        'token' => 'ODYTfxcvdbdfghdsfgdfsgdsfgsdfgsdfgdfgU',
]);

$discord->on('ready', function ($discord) {
        $discord->on(Event::GUILD_MEMBER_ADD, function ($member, $discord) {
                echo "Hello World";
                $channel = $discord->getChannel('88963127178263045726');
                $channel->sendMessage("Hello World");
        });
});

$discord->run();

```
On my local server, when a new member join the guild, this script output "Hello World" in my terminal and post "Hello World" message on the channel. On production server, it does nothing.
I tried to run the script on PHP 8 but the issue still there.

I can provide more informations if you want. phpinfo, php.ini... Just ask.

Thank you very much for your help.

**Comment by davidcole1340** [comment]
You need to enable the `GUILD_MEMBERS` intent in the Discord developer portal as well as in your client options. See the [documentation](http://discord-php.github.io/DiscordPHP/) sections, more specifically the "There are less members and/or users than expected" FAQ section as well as the "Guild Member Add" event section.

**Comment by Jarode01** [comment]
Thanks !
