### ISSUE TITLE
$guild->members is NULL

### ISSUE THREAD

**Issue by Jarode01** [discord-php/DiscordPHP#566]
Hi ,

**My script**
```php
include __DIR__.'/vendor/autoload.php';

use Discord\Discord;
use Discord\WebSockets\Intents;
use Discord\WebSockets\Event;

$discord = new Discord([
    'token' => 'ODYTMWU',
    'loadAllMembers' => true,
    'intents' => Intents::getDefaultIntents() | Intents::GUILD_MEMBERS // Enable the `GUILD_MEMBERS` intent
]);

$discord->on('ready', function ($discord)
{
    $guild = $discord->guilds->fetch('865991569635404052');
    var_dump($guild->members); //output NULL
});

$discord->run();
```
In the exemple above, $guild->members is NULL.

NB : "PRESENCE INTENT" and "SERVER MEMBERS INTENT" are checked in my bot settings

Thanks

**Comment by davidcole1340** [comment]
`$discord->guilds->fetch()` returns a promise as it has the potential to wait on an HTTP request from Discord. You don't need to do this for guilds as there is no potential for them to be missing from the cache. Use the `get` function instead:

```php
$guild = $discord->guilds->get('id', 'guild_id_here');
```

**Comment by Jarode01** [comment]
Perfect ! Thank you again. :)
