### ISSUE TITLE
MessageReaction class fatal error

### ISSUE THREAD

**Issue by Valkinaz** [discord-php/DiscordPHP#567]
**Environment**
- PHP Version:
    - PHP 7.4.3
- DiscordPHP Version:
    - 6.0.1

**Describe the bug**
PHP Fatal error:  Uncaught TypeError: Return value of Discord\Parts\WebSockets\MessageReaction::getMemberAttribute() must be an instance of Discord\Parts\User\Member or null, instance of stdClass returned.

**To Reproduce**
```php
$discord->on(Event::MESSAGE_REACTION_ADD, function (MessageReaction $reaction, Discord $discord) {
    $reaction->getPublicAttributes();
});
```

**Expected behavior**
Returns valid data array

**Comment by davidcole1340** [comment]
This has already been fixed on the `master` branch (see #532). You can update by changing the version of `discord-php` to `dev-master` inside your `composer.json` file, otherwise I will push a release sometime this week.
