### ISSUE TITLE
How do I send a message?

### ISSUE THREAD

**Issue by tpguy825** [discord-php/DiscordPHP#568]
When copying and pasting from the docs it says “cannot find MessageBuilder” and when copying and pasting from the wiki it says “$channel is undefined”. Is there a simple way to define it or not?

**Comment by davidcole1340** [comment]
The current docs are for the `develop` version of DiscordPHP. You can enable this by running `composer require team-reflex/discord-php dev-develop`.

As for the `$channel is undefined`, you need to define it somewhere. We don't know where you want to send the message.

**Comment by Tricky12321** [comment]
I cannot get the the message part to work

`
$message = MessageBuilder::new()->setContent('Hello, world!');
$discord->getChannel(xxxxxxxxxxx)->sendMessage($message)->done(function (Message $message) {
     echo "Message sent!";
});;
`

**Comment by picachuat** [comment]
$channel = $message->channel;
