### ISSUE TITLE
Front page typo

### ISSUE THREAD

**Issue by kangarko** [discord-php/DiscordPHP#574]
https://github.com/discord-php/DiscordPHP#installing-discordphp

"This will install the _lastest_ release."

**Comment by SQKo** [comment]
The class reference should also directly link to https://discord-php.github.io/DiscordPHP/reference/


https://github.com/discord-php/DiscordPHP/blob/78c8bc408b29adb611f358278896debcadb509cd/README.md#L91

to:

```
Documentation can be found [here](//discord-php.github.io/DiscordPHP). Raw documentation can be found in-line in the code and on the [DiscordPHP Class Reference](//discord-php.github.io/DiscordPHP/reference/).
```
(using // so http/https link will follow automatically)

**Comment by davidcole1340** [comment]
Thanks
