### ISSUE TITLE
What About MessageBuilder, Components, Interactions

### ISSUE THREAD

**Issue by Ixiter** [discord-php/DiscordPHP#577]
**Is your feature request related to a problem? Please describe.**
I read about the MessageBuilder and adding components in the documentation. In the history I saw the builder was removed.
Will it come back?
How can we use Components?
How can we receive interactions with a Bot?

**Describe the solution you'd like**
Complete implementation of Components and interactions

**Comment by davidcole1340** [comment]
The `MessageBuilder` class is present in the `develop` version, change the `discord-php` version to `dev-develop` in your `composer.json` and run `composer update`.

**Comment by Ixiter** [comment]
Thank you for you quick answer. Yeps .. read that on your Discord > Announcements channel already and updated to dev-develop.
