### ISSUE TITLE
getAuditLog() returns message: "Value \":guild_id\" is not snowflake." 

### ISSUE THREAD

**Issue by kowalski-lukasz** [discord-php/DiscordPHP#592]
**Environment**
- PHP Version:
    - 7.4.1
- DiscordPHP Version:
    -  dev-develop

**Describe the bug**
getAuditLog() returns exception 50035 -> message: "Value \":guild_id\" is not snowflake." 

```php
$guild = $discord->guilds->get('id', '123456');
                $guild->getAuditLog([
                    'action_type' => Entry::MESSAGE_DELETE
                ])->done(function (AuditLog $auditLog) {
                    foreach ($auditLog->audit_log_entries as $entry) {
                        var_dump($entry);
                    }
                });
```

**Comment by oliverschloebe** [comment]
This is actually not a bug but Discord API specification. Just change `guilds->get('id', '123456')` to `guilds->get('id', 123456)`;
`guild_id` must be an integer/snowflake.

**Comment by kowalski-lukasz** [comment]
> This is actually not a bug but Discord API specification. Just change `guilds->get('id', '123456')` to `guilds->get('id', 123456);`
> `guild_id` must be an integer/snowflake.

I changed `guilds->get('id', '123456')` to `guilds->get('id', 123456);` and I have the same error

**Comment by davidcole1340** [comment]
Please try the latest `master` branch
