### ISSUE TITLE
How to use isSpeaking?

### ISSUE THREAD

**Issue by degoya** [discord-php/DiscordPHP#605]
i'd like to check if the bot is playing a audio before stopping it.
can someone point me on a solution to do this?

`
   if($client->isSpeaking) {
      $client->close();
  }
`
is not working because osSpeaking required the ID of the Person, but i don't know how to get the id.

**Comment by valzargaming** [comment]
$client->user->id

**Comment by degoya** [comment]
this gives me an Undefined property error.

`
            if (strpos($str, '!stop') !== false) {
                echo ('!stop');
                if ($client = $discord->getVoiceClient($message->channel->guild_id)) { 
                     if($client->isSpeaking($client->user->id)) {
                        $client->close();
                    } else {
                        $message->reply('not playing anything i could stop');
                    }
                }
            }
`

**Comment by valzargaming** [comment]
Sorry, I thought you were using $client as your instance of DiscordPHP. It should be $discord->user->id

**Comment by degoya** [comment]
now i get a id but the client isn't closing because $client->isSpeaking($client->user->id) is not true, but it is playing.

**Comment by key2peace** [comment]
$client->stop(), see [voiceclient->stop()](https://github.com/discord-php/DiscordPHP/blob/master/src/Discord/Voice/VoiceClient.php#L1083-L1097)

**Comment by key2peace** [comment]
> now i get a id but the client isn't closing because $client->isSpeaking($client->user->id) is not true, but it is playing.

$client->isSpeaking($message->user->id)

**Comment by key2peace** [comment]
please update dev-master, should be ok now
