### ISSUE TITLE
I can't add roles to users

### ISSUE THREAD

**Issue by dltkddnr04** [discord-php/DiscordPHP#611]
```
if (strtolower($message->content) == '!role') {
  $member->addRole('xxxxxxxxxxxx')
}
```
I want to write code that adds a role when the user inputs a command.
But the code is not working. Can anyone give me details?

**Comment by SQKo** [comment]
Please provided the errors here, there are many possible reasons:

- `$member` is null, please use `$message->author->member` instead
- role id 'xxxxxxxxxxxx' is invalid (must be valid role snowflake id of the guild)
- the bot has no permission to manage user roles

**Comment by dltkddnr04** [comment]
solved
The first was the solution to the problem.
thanks.
