### ISSUE TITLE
Can not start bot.

### ISSUE THREAD

**Issue by sussy-baka-imposter** [discord-php/DiscordPHP#616]
**Environment**
- PHP Version:
    - 7.4
- DiscordPHP Version:
    - 6.0

**Describe the bug**
Can not start a bot.

**To Reproduce**
```php
<?php

require "vendor/autoload.php";

define("BOT_TOKEN", "MY_TOKEN");

use Discord\Discord;

$client = new Discord([
    "token" => BOT_TOKEN,
]);

$client->on("ready", function($message, $client) {
    echo "Bot has already...\n";
});
```
When I run file it has an error: 
```
[2021-11-01T14:11:45.870092+00:00] DiscordPHP.DEBUG: BUCKET getoauth2/applications/@me queued REQ GET oauth2/applications/@me [] []
[2021-11-01T14:11:45.880655+00:00] DiscordPHP.DEBUG: BUCKET getgateway/bot queued REQ GET gateway/bot [] []
```

**Comment by SQKo** [comment]
Nothing wrong with the messages, It's not an error.

Try update your DiscordPHP library to latest (dev-master, version 7.0.0)

**Comment by davidcole1340** [comment]
You are missing a `$discord->run()` as the last line of your code

**Comment by shehi** [comment]
Why everyone can tag and assign issues?!
