### ISSUE TITLE
Unavailable servers prevent setupChunking()

### ISSUE THREAD

**Issue by valzargaming** [discord-php/DiscordPHP#620]
https://github.com/discord-php/DiscordPHP/blob/cf79ca6ada74102b50ade8f84d99db028d585505/src/Discord/Discord.php#L459

setupChunking never gets called if something goes wrong and a server that is expected to load never loads. Removing this if statement or calling setupChunking() after a set amount of time has passed resolves the issue and allows start-up functions such as with loadAllMembers to process correctly. This issue occurs if an empty guild is sent by Discord but neither a guild create or guild delete event is called for that guild by Discord.

https://discord.com/developers/docs/topics/gateway#guild-availability
https://discord.com/developers/docs/topics/gateway#guild-create

# Before
![image](https://user-images.githubusercontent.com/7202504/140866687-ab644f5e-4c30-4c0f-83cc-363673de6fb6.png)

# After
![image](https://user-images.githubusercontent.com/7202504/140866706-46284104-899f-46d7-b1ae-bee6cf8e2461.png)

**Comment by valzargaming** [comment]
This issue has resurfaced when using the new cache interface if the external cache is not available.

**Comment by SQKo** [comment]
> This issue has resurfaced when using the new cache interface if the external cache is not available.

The cache is never read on the Guild Members Chunk I don't believe that was the issue.
