### ISSUE TITLE
Buttons question

### ISSUE THREAD

**Issue by iZeaoGamer** [discord-php/DiscordPHP#632]
Hey, so I am currently using this API to code my bot, and it lead to an issue. Not sure if it's on your end, or if it's on my end. But I've created buttons for my bot, and there is an issue where it'd say "This interaction has failed" message 3 seconds after the button was initially pressed. I have made button responses via Interaction Create event, not sure if this is the cause or not, but just let me know what I'm doing wrong. Also, there is no error in console. Thank you!

**Comment by SQKo** [comment]
If you want to handle buttons events, use `setListener()`, or manually respond the interaction with ping via endpoint.

**Comment by iZeaoGamer** [comment]
Okay, I’ll test it shortly and let you know if it works or not.

**Comment by iZeaoGamer** [comment]
Is there a way to use Interaction class without the use of setListener?

**Comment by SQKo** [comment]
Yes just use
```php
$discord->on(Event::INTERACTION_CREATE, function (Interaction $interaction, Discord $discord) {
    // code here
});
```

**Comment by iZeaoGamer** [comment]
Okay, thanks. It works
