### ISSUE TITLE
Reply to a message

### ISSUE THREAD

**Issue by m00nm00nm00n** [discord-php/DiscordPHP#644]
How can I reply to a message? I can get it to the point where I can recognize a command but unsure how to reply to the message. Thank you!

         $discord->on('message', function ($message, $discord) {
                echo "{$message->author->username}: {$message->content}",PHP_EOL;
	    	if ($message->content == 'yessir') {
			
			echo 'yep';
			
			$builder = MessageBuilder::new();
			
			$channel->sendMessage(MessageBuilder::new()
			->setContent('Hello, world!')
			);
			
			$builder->setContent('Hello, world!');
			
			$builder->setTts(true);
			
			// $builder->addEmbed($embed);
			
			// $embeds = [...];
			// $builder->setEmbeds($embeds);

			$discord->on(Event::MESSAGE_CREATE, function (Message $message) use ($builder) {
				$builder->setReplyTo($message);
			});
			
		}
    });

**Comment by SQKo** [comment]
Reply a `$message` with simple text:
```php
$message->reply("Hi");
```

Reply a `$message` with Message Builder:
```php
$messagebuilder = MessageBuilder::new();
// ...
$messagebuilder->setReplyTo($message);
// ...
$message->channel->send($messagebuilder);
```
