### ISSUE TITLE
\Discord\Voice\VoiceClient::close does not function properly

### ISSUE THREAD

**Issue by ajpircio** [discord-php/DiscordPHP#668]
**Environment**
- PHP Version:
    - 8.0
- DiscordPHP Version:
    - 6.0.2

**Describe the bug**
The close function calls the "stop()" method which unless audio is playing, will result in an exception. This prevents the code from continuing, and prevents the voice client from disconnecting from a channel properly

**To Reproduce**
```php
$discord->joinVoiceChannel($channel)->then(function (\Discord\Voice\VoiceClient $voiceClient) {
    try {
    	$voiceClient->close();
    }
    catch (\Exception $e) {
    	// $e->getMessage() returns "Audio must be playing to stop it"
    }
});
```

**Expected behavior**
The voice client should ignore the exception triggered in stop(), or at least add a check prior to stop to see if needs to be stoped

**Additional context**
Manually modifying the vendor files to ignore the exception allow the voice client to close appropriately

**Comment by key2peace** [comment]
will be fixed one #669 is committed :)

**Comment by SQKo** [comment]
Try again in the latest `dev-master`

**Comment by Cydeamon** [comment]
Thank you! I'll definitely try it!
