### ISSUE TITLE
Bot suddenly loses permission to post to channel (without any changes!)

### ISSUE THREAD

**Issue by Swift42** [discord-php/DiscordPHP#674]
**Environment**
- PHP Version:
    - 8.0
- DiscordPHP Version:
    - dev-master 74fbd0e

**Describe the bug**

I have a very weird problem.

My bot has the posting permission for a specific channel. After some time/restarts the bot suddenly (without ANY changes to the bot or the channel!) loses the ability to post and I get the message:

_There was an error sending the message: You do not have permission to send messages in the specified channel._

Sometimes this could be fixed by simply saving the channel's permissions again in discord (without making any change or making a change to some other permission!)

This was driving me nuts.
After weeks of investigating, I come to the conclusion that it has to be on DiscordPHP side, because DiscordPHP checks the permissions by its own before sending the message.

According to Discord's documentation the permissions are applied in this order:

```
1) Apply denies of @everyone on channel
2) Apply allows of @everyone on channel
3) Sum up all the denies of a member's roles and apply them at once
4) Sum up all the allows of a member's roles and apply them at once
5) Apply denies for a specific member if they exist
6) Apply allows for a specific member if they exist
```
So the order of roles should make no difference, because first all denies are summed up, then all allows.
Does DiscordPHP maybe mess up the order of this permission hierarchy?

To clarify the current situation:
The bot has 2 roles, let's say A and B.

The channel has these permissions for "posting messages":
everyone: deny
A: deny
B: allow

According to the Discord documentation, the bot should have the permission to post a message, because the "allow" from role "B" is applied at the very end.
So maybe DiscordPHP applies the permissions sometimes in the wrong order, e.g. first from role "B" (allow) and then from role "A" (deny)?

I tried to fix this problem and changed the channels permissions to:
everyone: deny
A: neutral
B: allow

This seems to work permanently, but the underlying problem is still there.

**Comment by SQKo** [comment]
We've just recently changed our permission codes a week after 74fbd0e, give it a try if that fix it
Please keep your DiscordPHP up to date with dev-master if you are using the v7.0.0-RC features

Otherwise we might need to look more into it

**Comment by Swift42** [comment]
Thanks for the feedback.
I'm running 64 bit PHP, but I updated my DiscordPHP to the latest dev version now (dev-master ad5b64a).
I will switch back the permissions to its original state (everyone: deny, A: deny, B: allow) and see if it's fixed now.

I will give feedback here.
But it can take some weeks, because the problem sometimes arises the next day already, sometimes it works for weeks before the problem suddenly happens.

**Comment by SQKo** [comment]
It shouldn't happen in a week or more... One of possible reason is that DiscordPHP has unsynced permission value in the cache, as you explained that saving the same permission fixes it, that's just DiscordPHP syncing the changes.

We will try to reproduce this, but please completely show what you permissions enabled in:
`@everyone` role
All the bots role, along with the role positions
The channel permissions to the Bot roles or the Bot user

**Comment by Swift42** [comment]
Oh, that was fast:
I can confirm that the update did **not** fix the problem.

I reversed the permissions to its original state (everyone: deny, A: deny, B: allow) and the bot instantly cannot post to the channel anymore.
But role B should allow the posting of messages, because it should be applied last.

**Comment by SQKo** [comment]
Role B must be above the role A for that to work, otherwise dont set deny for role A, or remove role A from the bot


It'd be useful if you provide us screenshot of the permission settings so we can reproduce it

**Comment by Swift42** [comment]
I attached a full permission overview of the three roles (everyone, A, B).
As you can see, role B should grant ALL permissions, including the "post messages" permission.

You wrote "Role B must be above the role A for that to work": That is not correct. 
Discord changed this some months ago. Have a look here: https://support.discord.com/hc/en-us/articles/206141927-How-is-the-permission-hierarchy-structured-
The order of roles doesn't play a role anymore!

![discordphp](https://user-images.githubusercontent.com/1180176/148572704-988854c1-7d64-4319-9ddc-92bd4dde768e.png)

**Comment by Swift42** [comment]
> We also need the permissions from the Role

Do you mean the server permissions for the roles? If yes: I attached them.
(left: role A, right: role B)

![discordphp2](https://user-images.githubusercontent.com/1180176/148575282-f61d0c07-0b9a-4da5-a16a-04e412bd359e.png)

**Comment by SQKo** [comment]
> > We also need the permissions from the Role
> 
> Do you mean the server permissions for the roles? If yes: I attached them. (left: role A, right: role B)
Yes! And also the everyone roles please.

**Comment by Swift42** [comment]
Here the server permissions for @everyone:
(thank you very much in advance for your help!)

![discordphp3](https://user-images.githubusercontent.com/1180176/148576051-7f87d5ed-0eb2-47e1-ae51-93e1ac426c04.png)

**Comment by SQKo** [comment]
Alright thank you, we will try to reproduce it...

Just a tip about permission overwrites: If you completely are not allowing `@everyone` in a channel, just deny "View channel". It is not necessary to deny the rest permissions.

**Comment by Swift42** [comment]
If I can help with more screenshots or debug msgs, give me a ping.
I really want this to be fixed, because problems that occur only sometimes are really the worst problems. :-)
I hope you can reproduce this.

**Comment by SQKo** [comment]
So I've been able to reproduce it


So far the change is caused right here:
https://github.com/discord-php/DiscordPHP/blob/74fbd0efec4d66fcf4d99ac1346eb8076f0b0957/src/Discord/Parts/User/Member.php#L244-L245

https://github.com/discord-php/DiscordPHP/blob/74fbd0efec4d66fcf4d99ac1346eb8076f0b0957/src/Discord/Parts/User/Member.php#L254-L255

It's specifically bug for Channel Permission Overwrites.. But I haven't found the root problem yet.

**Comment by SQKo** [comment]
Please try on latest `dev-master`

**Comment by Swift42** [comment]
I tried the latest dev-master (717c753) and set the channel permissions back to its original state (everyone: deny, role1: deny, role2: allow).
My bot instantly got a permission error.
So it seems that the problem is not fixed.

But here comes the weird thing:
If I save the permissions from role 1 last in Discord, I get a permission error.
If I save the permissions from role 2 last in Discord, I get no permission error.
Despite the fact that in both cases the same permissions are saved and therefore the same permissions should be applied! 
So the order of the save plays a role, but this should not be so.

This can mean only one thing: My original assumption that DiscordPHP mixes up the permission order seems true.
Could it be that the order of permissions isn't applied as it was written in the Discord documentation?
https://support.discord.com/hc/en-us/articles/206141927-How-is-the-permission-hierarchy-structured-

For me it seems that for every role both the allows and denies are applied simultanously in DiscordPHP, but they should applied completely separated: First the denies for ALL roles, then the allows for ALL roles.

Because if you apply the deny from role 1 last, you don't have the permission, but according to the docs you should have the permission, because role 2 clearly overrides the deny with the allow.

**Comment by SQKo** [comment]
> I tried the latest dev-master ([717c753](https://github.com/discord-php/DiscordPHP/commit/717c7538bcc5a839ddab240b15e43d4e5cac2019)) and set the channel permissions back to its original state (everyone: deny, role1: deny, role2: allow). My bot instantly got a permission error. So it seems that the problem is not fixed.

Thank you for confirming, I was able to reproduce it and the issue didnt persists.

> But here comes the weird thing: If I save the permissions from role 1 last in Discord, I get a permission error. If I save the permissions from role 2 last in Discord, I get no permission error. Despite the fact that in both cases the same permissions are saved and therefore the same permissions should be applied! So the order of the save plays a role, but this should not be so.

This however like my first assumption, is caused by caching issue, which I did not found in the code

> This can mean only one thing: My original assumption that DiscordPHP mixes up the permission order seems true. Could it be that the order of permissions isn't applied as it was written in the Discord documentation? https://support.discord.com/hc/en-us/articles/206141927-How-is-the-permission-hierarchy-structured-
> 
> For me it seems that for every role both the allows and denies are applied simultanously in DiscordPHP, but they should applied completely separated: First the denies for ALL roles, then the allows for ALL roles.
> 
> Because if you apply the deny from role 1 last, you don't have the permission, but according to the docs you should have the permission, because role 2 clearly overrides the deny with the allow.


Nope, the code applies it correctly following Discord instructions, there is no order involved because all permission bits takes calculation, e.g. 1-1+1 or 1+1-1 the result in the end is always the same (ofcourse its not literally plus and minus operation).

We might need to debug this later with cache issue

Probably related to #678

**Comment by Swift42** [comment]
Are you sure? For me it seems that the order is really incorrect.
I tried to apply the permissions in the correct order (first deny for all roles, then the allow for all roles).
So when I change this in DiscordPHP/src/Discord/Parts/User/Member.php:
```
            /* @var Overwrite */
            foreach ($channel->overwrites as $overwrite) {
                if ($overwrite->type !== Overwrite::TYPE_ROLE || ! in_array($overwrite->id, $roles)) {
                    continue;
                }

                $bitwise = Bitwise::or($bitwise, $overwrite->allow->bitwise);
                $bitwise = Bitwise::and($bitwise, Bitwise::not($overwrite->deny->bitwise));
            }
```
to:
```
            /* @var Overwrite */
            foreach ($channel->overwrites as $overwrite) {
                if ($overwrite->type !== Overwrite::TYPE_ROLE || ! in_array($overwrite->id, $roles)) {
                    continue;
                }

                $bitwise = Bitwise::and($bitwise, Bitwise::not($overwrite->deny->bitwise));
            }

            foreach ($channel->overwrites as $overwrite) {
                if ($overwrite->type !== Overwrite::TYPE_ROLE || ! in_array($overwrite->id, $roles)) {
                    continue;
                }

                $bitwise = Bitwise::or($bitwise, $overwrite->allow->bitwise);
            }
```

Everything works as expected!
I now get no permission error no matter in which order I save the roles.

Maybe I'm wrong with my assumptions, but nevertheless it works now.

**Comment by Swift42** [comment]
You wrote "Nope, the code applies it correctly following Discord instructions, there is no order involved because all permission bits takes calculation, e.g. 1-1+1 or 1+1-1 the result in the end is always the same (ofcourse its not literally plus and minus operation)."

This is not always true:

Bitwise:
Deny AND Deny OR Allow = Allow
Deny OR Allow AND Deny = Deny

**Comment by SQKo** [comment]
> You wrote "Nope, the code applies it correctly following Discord instructions, there is no order involved because all permission bits takes calculation, e.g. 1-1+1 or 1+1-1 the result in the end is always the same (ofcourse its not literally plus and minus operation)."
> 
> This is not always true:
> 
> Bitwise: Deny AND Deny OR Allow = Allow Deny OR Allow AND Deny = Deny

It's already like that
i was just explaining you the orders takes no effect in the calculation

**Comment by Swift42** [comment]
Ok, you are the expert here. I revert my changes and I hope you can fix the underlying problem.

I do not know where the error is in my thinking, because as far as I can see, the original code applies the permissions for the roles one by one in a bitwise manner:
Deny=0, Allow=1
Order of roles: everyone, role 1, role 2
0 AND 0 OR = 1 = allow
Order of roles: everyone, role 2, role 1
0 OR 1 AND 0 = 0 = deny

Maybe I'm understanding the bitwise application of the values wrong.
So again: You are the expert and you know the code better than me.
I hope you can find the problem.

Thanks for your patience with me. I really appreciate it :-)

**Comment by Swift42** [comment]
Oh, almost forgotten - I don't know if this helps: 
It makes no difference if I restart the bot or not. The problem persists until I change the order of the save.

**Comment by SQKo** [comment]
> Ok, you are the expert here. I revert my changes and I hope you can fix the underlying problem.
No worries, I had the same thought before, but after looking more, I was wrong about it

> I do not know where the error is in my thinking, because as far as I can see, the original code applies the permissions for the roles one by one in a bitwise manner: Deny=0, Allow=1 Order of roles: everyone, role 1, role 2 0 AND 0 OR = 1 = allow Order of roles: everyone, role 2, role 1 0 OR 1 AND 0 = 0 = deny
> 
> Maybe I'm understanding the bitwise application of the values wrong. So again: You are the expert and you know the code better than me. I hope you can find the problem.

The order makes no difference because each role are not calculates in order like that, its currenrly like this in the foreach iteration:
(role1) | (role2) | (role3)
so if for your case those are like
0 | 0 | 1 = 1 = allow
0 | 1 |  0 = 1 = allow

> Thanks for your patience with me. I really appreciate it :-)
> 
> If I can somehow help to find the problem, please give me a ping.

This seems to be randomly happen as you explained before, and my best guess is with cache (data is not synced properly) and thus we need to debug it deeply

> Oh, almost forgotten - I don't know if this helps:
It makes no difference if I restart the bot or not. The problem persists until I change the order of the save.

This can help, thank you

**Comment by SQKo** [comment]
We'd need to test this on different branch, so #680 use the `dev-patch-getpermissions` in your composer package

**Comment by SQKo** [comment]
I added some debugging code line in that function, so if possible please copy paste the output from your console to here.

**Comment by SQKo** [comment]
Okay so this is the same permission sets  as above after updating one of the role:
```
Array (     [269] => BEGIN CHANNEL OVERWRITE TEST     [bitwise] => 3072 )  [] []
Array (     [271] => TESTING ROLE @everyone     [bitwise] => 3072 )

Array (     [272] => bitwise &= ~deny     [bitwise] => 1024     [deny] => 2048 )  [] []
Array (     [273] => bitwise |= allow     [bitwise] => 1024     [allow] => 0 )  [] []
Array (     [280] => TESTING ROLE 894836570832666695     [bitwise] => 1024 )  [] []
Array (     [282] => bitwise &= ~deny     [bitwise] => 1024     [deny] => 0 )  [] []
Array (     [283] => bitwise |= allow     [bitwise] => 3072     [allow] => 2048 )  [] []
Array (     [280] => TESTING ROLE 932255053971075112     [bitwise] => 3072 )  [] []
Array (     [282] => bitwise &= ~deny     [bitwise] => 1024     [deny] => 2048 )  [] []
Array (     [283] => bitwise |= allow     [bitwise] => 1024     [allow] => 0 )  [] []
Array (     [290] => END OF TEST     [bitwise] => 1024 )  [] []
```

The order of role iterator cause changes in calculation, which @Swift42 said:
> It makes no difference if I restart the bot or not. The problem persists until I change the order of the save.

So discord keep that order of roles even after bot restart, which I was not able to reproduce the bug anymore. But it's back again once I update one of the role (just because i turn on/off the permission)

We believed that if we followed the pseudocode as demonstrated from https://discord.com/developers/docs/topics/permissions#permission-overwrites works fine, but apparently it behaves different in PHP (or in python?)

So we have to rewrite the implementation...

Thank you again for reporting the bug!

**Comment by Swift42** [comment]
If I compare both code snippets (PHP and Python), the PHP code applies the allows and denies simultanously (directly to the bit value).
But the python code first gathers all allows and denies separately and then applies them in the correct order (first the cumulated denies, then the cumulated allows) to the bit value.
So my first suspicion turns out to be correct :-)
This is the python code:

```
allow = NONE
deny = NONE
for role_id in member.roles:
        overwrite_role = overwrites.get(role_id)
        if overwrite_role:
            allow |= overwrite_role.allow
            deny |= overwrite_role.deny

permissions &= ~deny
permissions |= allow
```
I think this would be the correct PHP translation:

           /* @var Overwrite */
            $allow=0;
            $deny=0;
            foreach ($channel->overwrites as $overwrite) {
                if ($overwrite->type !== Overwrite::TYPE_ROLE || ! in_array($overwrite->id, $roles)) {
                    continue;
                }

                $allow |= $overwrite->allow->bitwise;
                $deny |= $overwrite->deny->bitwise;
            }
            $bitwise &= ~($deny);
            $bitwise |= $allow;

**Comment by SQKo** [comment]
> If I compare both code snippets (PHP and Python), the PHP code applies the allows and denies simultanously (directly to the bit value). But the python code first gathers all allows and denies separately and then applies them in the correct order (first the cumulated denies, then the cumulated allows) to the bit value. So my first suspicion turns out to be correct :-)
Yup, my bad. Turns out that I was actually only fixing a bug that only present on the dev verison. Since the order of the roles were given by Discord, I didn't notice it was another issue

> This is the python code:
> 
> ```
> allow = NONE
> deny = NONE
> for role_id in member.roles:
>         overwrite_role = overwrites.get(role_id)
>         if overwrite_role:
>             allow |= overwrite_role.allow
>             deny |= overwrite_role.deny
> 
> permissions &= ~deny
> permissions |= allow
> ```
> 
> I think this would be the correct PHP translation:
> 
> ```
>        /* @var Overwrite */
>         $allow=0;
>         $deny=0;
>         foreach ($channel->overwrites as $overwrite) {
>             if ($overwrite->type !== Overwrite::TYPE_ROLE || ! in_array($overwrite->id, $roles)) {
>                 continue;
>             }
> 
>             $allow |= $overwrite->allow->bitwise;
>             $deny |= $overwrite->deny->bitwise;
>         }
>         $bitwise &= ~($deny);
>         $bitwise |= $allow;
> ```

Yup that should be correct, I was not the person who wrote the code, so I tried to consult them.
The difference is indeed that we are using object of the RolePermission to calculate the bitwise, while the python approach was using a simple variable to keep the bitwise (and even resets it to None before going to other type of overwrites). That would make difference since object are copied by reference and simple variable are copied by value.

However since the added support with 32-bits PHP, we cannot just use the bitwise operators, instead we use the Bitwise helper class function, it would need a temporary variable as a buffer. I'll take a look on this later.

**Comment by SQKo** [comment]
@Swift42 please try `dev-patch-getpermissions`

**Comment by Swift42** [comment]
I think there is an error in lines 310 to 313. 
The comment reads correct "deny" and "allow", but in the actual code you've used "deny" twice and "allow" isn't used:

```
            // Set role "DENY" permissions overwrite
            $bitwise = Bitwise::and($bitwise, Bitwise::not($deny));
            // Set role "ALLOW" permissions overwrite
            $bitwise = Bitwise::and($bitwise, Bitwise::not($deny));
```

**Comment by SQKo** [comment]
> I think there is an error in lines 310 to 313. The comment reads correct "deny" and "allow", but in the actual code you've used "deny" twice and "allow" isn't used:
> 
> ```
>             // Set role "DENY" permissions overwrite
>             $bitwise = Bitwise::and($bitwise, Bitwise::not($deny));
>             // Set role "ALLOW" permissions overwrite
>             $bitwise = Bitwise::and($bitwise, Bitwise::not($deny));
> ```

Oops, fixed.

**Comment by SQKo** [comment]
@Swift42 can you confirm if it's fixed? I've tried to reproduce it with minimal code and it does not happen anymore.

**Comment by Swift42** [comment]
Yes! It seems that we finally fixed it.
I saved the roles in different orders and it always worked as expected.
Thanks for your help!
The patch can go live.
