### ISSUE TITLE
Webhook create and read url

### ISSUE THREAD

**Issue by streamthing** [discord-php/DiscordPHP#681]
Can Discord PHP create webhook and read it's url?
I don't see this in documentation http://discord-php.github.io/DiscordPHP

**Comment by valzargaming** [comment]
There is a [webhook repository](https://github.com/discord-php/DiscordPHP/blob/cd0fdd16217c7f1b7ff99c5a1a99c6cb36afccf9/src/Discord/Repository/Channel/WebhookRepository.php) which can be accessed from any channel where webhooks are supported, so theoretically yet, you could create one with factory and save it. Something like this:
```php
$data = [];
$webhook = $discord->factory->create(Webhook::class, $data, true);
$channel->webhooks->save($webhook)->done(function($webhook){
  var_dump($webhook)
});
```
This code is untested, but I bet it'd work.

**Comment by SQKo** [comment]
Currently in PR
https://github.com/discord-php/DiscordPHP/pull/677/files#diff-13da36a7279497674d02434368968dfd2d7ad873564df14fbd292f2d755d4f16

**Comment by SQKo** [comment]
Apparently I was wrong, the "url" in the attribute is not mean for bot or user created webhooks.

To get the "URL" you wanted to execute, simply format the link:
`https://discord.com/api/webhooks/{$webhook->id}/{$webhook->token}`

**Comment by key2peace** [comment]
no confirmation received within 2 weeks
