### ISSUE TITLE
How to know if someone is speaking on a vocie channel

### ISSUE THREAD

**Issue by AxioDev** [discord-php/DiscordPHP#686]
Hello,

Thanks you very much for this awesome project, i wonder how to know if someone is speaking on a voice channel. My aim is to create a bot that calculate the voice time of users in a voice channel, but i found nothing on the documentation but i saw that there is "VoiceClient" class, but i don't how to to use it

Can you help me ?

**Comment by key2peace** [comment]
#639 actually provides a nice example
