### ISSUE TITLE
How to reply to a message with message builder

### ISSUE THREAD

**Issue by chasecattaneo** [discord-php/DiscordPHP#690]
Hi,

I'm running into an issue where the message response is too long with the standard $message->reply();

How can I incorporate message builder to create a formatted response? I am responding with stock prices and I have seen a bulletin type format but not sure how to use it.

I am using the standard example code for a two way Discord bot so is it possible to incorporate it into the $message->reply() function?

Thanks!

**Comment by SQKo** [comment]
To reply a message with MessageBuilder, use `$messagebuilder->setReplyTo($message)`

Although that does not seem to be your issue with long message. Max content is 2000 characters, embed can have up to 4096 characters, however in total of combination you can only send up to 6000 characters.

Not sure what you mean with bulletin type format, but if you are talking embed, that's it. If you are talking about webhook, it cannot have message referenced as a reply.
