### ISSUE TITLE
About me question

### ISSUE THREAD

**Issue by iZeaoGamer** [discord-php/DiscordPHP#693]
Hey. Thanks for making this project!

I’d like to ask is there a way to fire an event when a User or bot updates their about me? 
Or is there an event already that fires when the user updates their about me also?

I’ve tried looking everywhere, but couldn’t find anything.

**Comment by SQKo** [comment]
Other user's update of non member attributes, which is the "about me" as you mentioned, is not received by the Bot in the API gateway events.

However an update to member attributes like nickname or username can be received from `Event::GUILD_MEMBER_UPDATE`

You can listen event for your own Bot "about me" (description) changes from the new `Event::USER_UPDATE` added in latest v7.0.0-RC3.

That's all I know, if you somewhat found that this is possible in another library, please let me know.

**Comment by iZeaoGamer** [comment]
Okay, thanks for the quick reply!

**Comment by iZeaoGamer** [comment]
Because I feel like the about me changes already fires when a member is updated, as someone from my server updated their about me, and at the same time, the event fires. So my main question is how would I check if they old and new member’s about me’s are the same?

**Comment by SQKo** [comment]
Well you are right that the event is sometimes fired when someone updates their "about me". However the "about me" data is never exposed to Bots as per Discord privacy policy.

**Comment by iZeaoGamer** [comment]
Ohh ok, thanks for clarifying that up!

**Comment by iZeaoGamer** [comment]
One more thing - How would you say I should go about things on adding a member update event, adding that to a mod logs channel? I'm only asking due to the About me data not being exposed, and not 100% sure on how to implement this without the About me sometimes firing?

**Comment by SQKo** [comment]
As I explained before,
> The member update callback first parameter is the new member data and third parameter is the old member data.

You can just compare the both member new data and old data (they are different object, so using equal operator wont work), preferably from their attributes. So you shall post mod logs only if the known member attributes are changed.

**Comment by iZeaoGamer** [comment]
Okay, thank you!
