### ISSUE TITLE
0 as min value of Selectmenu does not work

### ISSUE THREAD

**Issue by MichaelBelgium** [discord-php/DiscordPHP#698]
**Environment**
- PHP Version:
    - 7.4.21
- DiscordPHP Version:
    - dev-develop b8dca03 => have to use develop as a previous issue i had got fixed on that branch

**Describe the bug**
Well like the title says, 0 as min value of Selectmenu does not work. You're still required to select 1 option, not 0.

**To Reproduce**

I was making a command when i stumbled upon it, I made a simplier command to see if it had the same issue, and it did:
```php
$discord->registerCommand('test', function (Message $message) use ($discord) {
    $builder = MessageBuilder::new();
    $builder->setContent('Testing');
    $builder->setReplyTo($message);

    $select = SelectMenu::new()
        ->setMinValues(0)
        ->setMaxValues(15);

    for ($i=0; $i < 15; $i++) { 
        $select->addOption(Option::new('Option ' . $i, 'value_' . $i));
    }

    $select->setListener(function (Interaction $interaction, Collection $options) {
        dump($options->map(fn(Option $option) => $option->getValue())->toArray());
    }, $discord);

    $builder->addComponent($select);

    $message->channel->sendMessage($builder);
});
```

I selected first "Option 2", then deselected, then selected "Option 3" and got this output from the listener:

```
array:1 [
  0 => "value_2"
]
array:1 [
  0 => "value_3"
]
```
Which is correct, but then i deselect everything it it says "select at least 1" (see screenshot)

**Expected behavior**
Able to select none

**Screenshots**
![image](https://user-images.githubusercontent.com/8951045/151666736-a9f15a88-65ee-4814-b43f-e5a32e07b8da.png)

**Additional context**
At this point i believe it might be an issue with the discord api? Because when i debug `$select->getMinValues()` it does return 0.

**Comment by SQKo** [comment]
Please try on latest `dev-master`

**Comment by MichaelBelgium** [comment]
Yes, works! Thanks for fixing so quickly!
