### ISSUE TITLE
Why Event:Guild_Member_Add dont works?

### ISSUE THREAD

**Issue by TimLiz** [discord-php/DiscordPHP#713]
`<?php
include __DIR__.'/vendor/autoload.php';

use Discord\Discord;
use Discord\WebSockets\Event;

$discord = new Discord([
    'token' => 'TOKEN', // Put your Bot token here (https://discord.com/developers/applications/)
]);

$discord->on('ready', function (Discord $discord) {

    $discord->on(Event::GUILD_MEMBER_ADD, function () {
        echo "Yes";
    });

});

$discord->run();`

**Comment by givinghawk** [comment]
bro, regenerate your token

**Comment by TimLiz** [comment]
> bro, regenerate your token

I already did it

**Comment by TimLiz** [comment]
I fixed that:

1. Added `'loadAllMembers' => true,`
2. Added `'intents' => Intents::getDefaultIntents() | Intents::GUILD_MEMBERS`
3. And replaced `$discord->on(Event::GUILD_MEMBER_ADD, function () {
    echo "Yes";
});` to `$discord->on('GUILD_MEMBER_ADD', function($member, $discord) {
        $channel = $discord->getchannel('938161349387747361');
        echo "Yes";
    });`
