### ISSUE TITLE
GuildMemberUpdate error

### ISSUE THREAD

**Issue by xWildFire** [discord-php/DiscordPHP#733]
**Environment**
- PHP Version:
    - 8.0.10
- DiscordPHP Version:
    - 7.0.0

**Describe the bug**

`[2022-02-21 16:14:15] Message: Call to a member function pushItem() on null
	File: /home/wildcord/wildcord/vendor/team-reflex/discord-php/src/Discord/WebSockets/Events/GuildMemberUpdate.php:43
	Trace:
		#0 /home/wildcord/wildcord/vendor/team-reflex/discord-php/src/Discord/Discord.php(736): Discord\WebSockets\Events\GuildMemberUpdate->handle()
#1 /home/wildcord/wildcord/vendor/team-reflex/discord-php/src/Discord/Discord.php(601): Discord\Discord->handleDispatch()
#2 /home/wildcord/wildcord/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Discord\Discord->handleWsMessage()
#3 /home/wildcord/wildcord/vendor/ratchet/pawl/src/WebSocket.php(72): Ratchet\Client\WebSocket->emit()
#4 /home/wildcord/wildcord/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(248): Ratchet\Client\WebSocket->Ratchet\Client\{closure}()
#5 /home/wildcord/wildcord/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(194): Ratchet\RFC6455\Messaging\MessageBuffer->processData()
#6 /home/wildcord/wildcord/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Ratchet\RFC6455\Messaging\MessageBuffer->onData()
#7 /home/wildcord/wildcord/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit()
#8 /home/wildcord/wildcord/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}()
#9 /home/wildcord/wildcord/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit()
#10 /home/wildcord/wildcord/vendor/react/event-loop/src/StreamSelectLoop.php(245): React\Stream\DuplexResourceStream->handleData()
#11 /home/wildcord/wildcord/vendor/react/event-loop/src/StreamSelectLoop.php(212): React\EventLoop\StreamSelectLoop->waitForStreamActivity()
#12 /home/wildcord/wildcord/src/WildCord/App.php(429): React\EventLoop\StreamSelectLoop->run()
#13 /home/wildcord/wildcord/bot.php(10): WildCord\App->run()
#14 {main}`

**To Reproduce**
Idk, sometimes on Guild Member Update

**Comment by SQKo** [comment]
Hmm this is strange, do you remember what and when this happened? It's odd that you receive this event when guild object is null

**Comment by SQKo** [comment]
$guild->members is fine to be empty so pushItem will fill that, but it can never be null (which the error says) as that's repository constructed along with the guild.

However I'm adding an extra code to ignore the possible missing event data, which is I doubt there is even any.
