### ISSUE TITLE
Event::READY not triggering

### ISSUE THREAD

**Issue by shehi** [discord-php/DiscordPHP#737]
Bot runs flawlessly, events like `GUILD_CREATE`, `GUILD_MEMBER_ADD` all trigger. But for some reason `READY` never does. Possible bug?

**Environment**
- PHP Version:
    - 8.0.x
- DiscordPHP Version:
    - 7.0.2

**Comment by key2peace** [comment]
how about showing some code on how you use ready?

**Comment by Corin123555** [comment]
Looks like Event::READY appears to be case sensitive.

So for example:
```php
<?php
require('vendor/autoload.php');

use Discord\Discord;

use Discord\WebSockets\Event;
use Discord\WebSockets\Intents;

$discord = new Discord([
	'token' => '',
	'intents' => Intents::getDefaultIntents() | Intents::GUILD_MEMBERS | Intents::GUILD_PRESENCES,
	'loadAllMembers' => true
]);

// Event::READY resolves to 'READY'
$discord->on(Event::READY, function (Discord $discord) {
	echo "ready";
});

$discord->run();
```
Wont fire, but replace that with just `ready` instead and it'll work
