### ISSUE TITLE
Button Clicked question

### ISSUE THREAD

**Issue by iZeaoGamer** [discord-php/DiscordPHP#747]
Hey. So I was planning to implement a buttons clicked event. I know there is the Button->setListener(), but how can I add that to the button that was clicked? So if there were 5 buttons, and one of them was clicked, how would you go about with responding to that given component? I hope you can get back to me soon! Thank you.

**Comment by key2peace** [comment]
$button->setListener(function (Interaction $interaction) {});

**Comment by iZeaoGamer** [comment]
Sure, one second.

**Comment by iZeaoGamer** [comment]
foreach ($builder->getComponents() as $component) {
            print_r("Components responding..\n");
            if ($component instanceof \Discord\Builders\Components\ActionRow) {
                print_r("Action Row responding..\n");
                foreach ($component->getComponents() as $componentButton) {
                    print_r("Buttton Responding..\n");
                    if ($componentButton instanceof \Discord\Builders\Components\Button) {

                        if ($componentButton->getCustomId() === $custom_id) {
                            print_r("Button Custom ID: {$componentButton->getCustomId()} is the same as {$custom_id}\n");
                            $componentButton->setListener(function (DiscordInteraction $interaction) use ($action, $pk, $builder) {
                                print_r("Button Responded with.\n");
                                try {
                                    $interaction->acknowledge()->then(function () use ($interaction, $action, $pk, $builder) {
                                        // if($action === $pk::SEND_FOLLOW_UP){
                                        $this->setActionType($interaction, $pk, $builder, $action);
                                    }, function (\Throwable $e) use ($interaction, $builder, $action, $pk){
                                       // $this->setActionType($interaction, $pk, $builder, $action);
                                        print_r("There was an error whilst acknowledging response. {$e->getMessage()}");
                                    });
                                }catch(\Throwable $e){
                                //    $this->setActionType($interaction, $pk, $builder, $action);
                                }
                            }, $this->client->getDiscordClient(), $pk->isOneOff());
                        }
                    }
                }
            }

**Comment by SQKo** [comment]
Can you explain the code? Those "responding" print sounds unusual as normally you do not use the builder codes as "response".

**Comment by iZeaoGamer** [comment]
The print_r is for testing purposes. If I'm not meant to use MessageBuilder for responding to an ephemeral message in this case, then could you tell me of a way to use the ephemeral message response?

**Comment by SQKo** [comment]
While I'm not aware of your attempt on responding message as ephemeral, here is the general example:
```php
$interaction->respondWithMessage(MessageBuilder::new()->setContent('This is ephemeral'), true);
```
or:
```php
$builder = MessageBuilder::new();
$builder->setContent('This is ephemeral')->_setFlags(64);

$interaction->respondWithMessage($builder);
```

**Comment by SQKo** [comment]
fetch?
the Interaction is created on `setListener()` functions or the `Event::INTERACTION_CREATE`

I think you do not understand the interaction flow...

If you the namespace mean import, it is
`use Discord\Parts\Interactions\Interaction;`

**Comment by iZeaoGamer** [comment]
> foreach ($builder->getComponents() as $component) { print_r("Components responding..\n"); if ($component instanceof \Discord\Builders\Components\ActionRow) { print_r("Action Row responding..\n"); foreach ($component->getComponents() as $componentButton) { print_r("Buttton Responding..\n"); if ($componentButton instanceof \Discord\Builders\Components\Button) {
> 
> ```
>                     if ($componentButton->getCustomId() === $custom_id) {
>                         print_r("Button Custom ID: {$componentButton->getCustomId()} is the same as {$custom_id}\n");
>                         $componentButton->setListener(function (DiscordInteraction $interaction) use ($action, $pk, $builder) {
>                             print_r("Button Responded with.\n");
>                             try {
>                                 $interaction->acknowledge()->then(function () use ($interaction, $action, $pk, $builder) {
>                                     // if($action === $pk::SEND_FOLLOW_UP){
>                                     $this->setActionType($interaction, $pk, $builder, $action);
>                                 }, function (\Throwable $e) use ($interaction, $builder, $action, $pk){
>                                    // $this->setActionType($interaction, $pk, $builder, $action);
>                                     print_r("There was an error whilst acknowledging response. {$e->getMessage()}");
>                                 });
>                             }catch(\Throwable $e){
>                             //    $this->setActionType($interaction, $pk, $builder, $action);
>                             }
>                         }, $this->client->getDiscordClient(), $pk->isOneOff());
>                     }
>                 }
>             }
>         }
> ```

I am so sorry. I miss understood. The print_r is for testing purposes, but that has nothing to do with this issue. I know you can't respond with Message Builders, but you can set a Message builder with components? How would I send a ephemeral message like dank memer? Because if I use setListener(), then wouldn't it send a message builder with components?

**Comment by SQKo** [comment]
Can you screenshot what dankmemer bot shows to you?

**Comment by iZeaoGamer** [comment]
> Can you screenshot what dankmemer bot shows to you?

Sure

**Comment by iZeaoGamer** [comment]
![DankMemer](https://user-images.githubusercontent.com/20418886/156342412-3d32b2e2-9314-4109-bcaf-f90ec337d267.PNG)

**Comment by SQKo** [comment]
And prior to "what was the emoji?"

**Comment by iZeaoGamer** [comment]
You want that screenshot too?

**Comment by SQKo** [comment]
Yes, to me it looks like interaction follow up

**Comment by iZeaoGamer** [comment]
![Emoji](https://user-images.githubusercontent.com/20418886/156342759-71c23fb0-af9f-4e45-a35f-4d9f82beeb08.PNG)

**Comment by SQKo** [comment]
As you can see, the interaction starts from a button press, and under the button setListener, it respond with ephemeral message, so it's actually 2 steps interaction.

**Comment by iZeaoGamer** [comment]
So updateOriginalMessage() basically allows you to remove the buttons after the interaction?

**Comment by iZeaoGamer** [comment]
UpdateInitial*

**Comment by SQKo** [comment]
> So updateOriginalMessage() basically allows you to remove the buttons after the interaction?

More like, you can update the message with any content, excluding the buttons

**Comment by iZeaoGamer** [comment]
Ah okay. Could you give me an example of this? If not, then that's fine.

**Comment by SQKo** [comment]
> While I'm not aware of your attempt on responding message as ephemeral, here is the general example:
> 
> ```
> $interaction->respondWithMessage(MessageBuilder::new()->setContent('This is ephemeral'), true);
> ```
> 
> or:
> 
> ```
> $builder = MessageBuilder::new();
> $builder->setContent('This is ephemeral')->_setFlags(64);
> 
> $interaction->respondWithMessage($builder);
> ```

same as this, except using `$interaction->updateOriginalResponse()`

**Comment by iZeaoGamer** [comment]
Alright, let me check if this works. I'll report back to you if it works or not. Thanks.

**Comment by iZeaoGamer** [comment]
I tried to do as you said, but it edits the button's message that was clicked, and doesn't send the message ephemeral.

Here's the code:
 $builder2 = MessageBuilder::new();
                                    $builder2->setContent($pk->getContent())->_setFlags(64);
                    
                                    $interaction->respondWithMessage($builder2, true);
                                    $interaction->updateOriginalResponse($builder2)->then(function(DiscordMessage $message) use ($pk){
                                    $this->resolveRequest($pk->getUID(), true, "Responded Interaction", [ModelConverter::genModelMessage($message)]);
                                    }, function (\Throwable $e) use ($pk){
                                        print_r("There was an error whilst sending Ephemeral message. {$e->getMessage()}");
                                    });

**Comment by iZeaoGamer** [comment]
Okay, I've fixed it. Thanks for helping!

**Comment by iZeaoGamer** [comment]
Hey. I've just discovered a small issue, which is to do with Buttons Listener. So basically, when you set a button listener, the Interaction Create Event isn't firing this event, until 2-3 button clicks. So if I was to click on a button, it wouldn't respond properly, but after 2-3 clicks per custom_id, it'll work. I think it's an issue on my end, but not sure of a way to fix it, so I hope you can help me with this. Thank you!

**Comment by SQKo** [comment]
I can't reproduce, was it temporary Discord issue? Is it still happening?

**Comment by iZeaoGamer** [comment]
> I can't reproduce, was it temporary Discord issue? Is it still happening? Make sure your discord client is up to date

It’s been happening for quite a while now.

**Comment by SQKo** [comment]
please provide your code

**Comment by iZeaoGamer** [comment]
Okay, one second.

**Comment by iZeaoGamer** [comment]
foreach ($builder->getComponents() as $component) {
            print_r("Components responding..\n");
            if ($component instanceof \Discord\Builders\Components\ActionRow) {
                print_r("Action Row responding..\n");
                foreach ($component->getComponents() as $componentButton) {
                   
                    print_r("Buttton Responding..\n");
                    if ($componentButton instanceof \Discord\Builders\Components\Button) {

                        if ($componentButton->getCustomId() === $custom_id) {
                           
                           
                            print_r("Button Custom ID: {$componentButton->getCustomId()} is the same as {$custom_id}\n");
                          
                            $componentButton->setListener(function (DiscordInteraction $interaction) use ($custom_id, $executor, $action, $pk, $builder) {
                                $id = $executor;
                                if($interaction->member !== null){
                                    $id = $interaction->member->id;
                                }
                                if($interaction->user !== null){
                                    $id = $interaction->user->id;
                                }
                               
                                print_r("Interaction Responded with.\n");
                                try {
                                    if($action === $pk::SEND_FOLLOW_UP){
                                        //    $builder->removeComponent($component);
                                        
                                            $interaction->updateMessage($builder);
                                           
                                            $count = $this->count[$custom_id . "." . $id] ?? 0;
                                            if($count === 0 and $id !== $executor){
                                                print_r("User ID: {$id} is not the same as Executor: {$executor}");
                                            $interaction->sendFollowUpMessage(MessageBuilder::new()->setContent($pk->getContent()), true)->then(function(DiscordMessage $message) use ($id, $custom_id, $pk){
                                                
                                                $this->resolveRequest($pk->getUID(), true, "Responded with success.", [ModelConverter::genModelMessage($message)]);
                                                $this->count[$custom_id . "." . $id] = 0;
                                            });
                                            //if(!isset($this->count[$custom_id . "." . $id])){
                                                $this->count[$custom_id . "." . $id] = 1;
                                          
                                        }
                                }else{

                                    $interaction->acknowledge()->then(function () use ($interaction, $action, $pk, $builder) {
                                        // if($action === $pk::SEND_FOLLOW_UP){
                                        $this->setActionType($interaction, $pk, $builder, $action);
                                    }, function (\Throwable $e) use ($interaction, $builder, $action, $pk){
                                       // $this->setActionType($interaction, $pk, $builder, $action);
                                        print_r("There was an error whilst acknowledging response. {$e->getMessage()}");
                                    });
                                }
                                }catch(\Throwable $e){
                                //    $this->setActionType($interaction, $pk, $builder, $action);
                                }
                            }, $this->client->getDiscordClient(), $pk->isOneOff());
                        }
                    }
                }
            }
            if ($component instanceof \Discord\Builders\Components\SelectMenu) {
                print_r("Interaction responding..\n");
                if ($component->getCustomId() === $custom_id) {
                    print_r("Select Menu Custom ID: {$component->getCustomId()} is the same as {$custom_id}\n");
                    if(!isset($this->count[$custom_id])){
                        $this->count[$custom_id] = 1;
                    }else{
                        $this->count[$custom_id] += 1;
                    }
                    $count = $this->count[$custom_id];
                    print_r("Select Menu Custom ID: {$component->getCustomId()} is the same as {$custom_id}\n");

              
                    $component->setListener(function (DiscordInteraction $interaction) use ($custom_id, $executor, $action, $pk, $builder) {
                        $id = $executor;
                                if($interaction->member !== null){
                                    $id = $interaction->member->id;
                                }
                                if($interaction->user !== null){
                                    $id = $interaction->user->id;
                                }
                                if(!isset($this->count[$custom_id . "." . $id])){
                                    $this->count[$custom_id . "." . $id] = 1;
                                }else{
                                    $this->count[$custom_id . "." . $id] += 1;
                                }
                        print_r("Interaction responded with.\n");
                        try {
                            if($action === $pk::SEND_FOLLOW_UP){
                                //    $builder->removeComponent($component);
                                
                                    $interaction->updateMessage($builder);
                                    $count = $this->count[$custom_id . "." . $id];
                                    if($count <= 1 and $id !== $executor){
                                    $interaction->sendFollowUpMessage(MessageBuilder::new()->setContent($pk->getContent()), true)->then(function(DiscordMessage $message) use ($pk){
                                        $this->resolveRequest($pk->getUID(), true, "Responded with success.", [ModelConverter::genModelMessage($message)]);
                                    });
                                }
                        }else{

                            $interaction->acknowledge()->then(function () use ($interaction, $action, $pk, $builder) {
                                // if($action === $pk::SEND_FOLLOW_UP){
                                $this->setActionType($interaction, $pk, $builder, $action);
                            }, function (\Throwable $e) use ($interaction, $builder, $action, $pk){
                               // $this->setActionType($interaction, $pk, $builder, $action);
                                print_r("There was an error whilst acknowledging response. {$e->getMessage()}");
                            });
                        }
                        }catch(\Throwable $e){
                        //    $this->setActionType($interaction, $pk, $builder, $action);
                        }
                    }, $this->client->getDiscordClient(), $pk->isOneOff());
                }
            }
        }

 public function setActionType(DiscordInteraction $interaction, RequestComponentRespond $pk, MessageBuilder $builder, int $action)
    {
        switch ($action) {
            case $pk::SEND_FOLLOW_UP:
            //    $interaction->sendFollowUpMessage($builder, $pk->isEphemeral())->then(function (DiscordMessage $message) use ($pk) {
                break;
            case $pk::UPDATE_FOLLOW_UP:
                $interaction->updateFollowUpMessage($pk->getMessageId(), $builder)->then(function (DiscordMessage $message) use ($pk) {
                    $this->resolveRequest($pk->getUID(), true, "Responded Interaction", [ModelConverter::genModelMessage($message)]);
                }, function (\Throwable $e) use ($pk){
                    print_r("There was an error whilst updating follow up message. {$e->getMessage()}");
                });
                break;
            case $pk::DELETE_FOLLOW_UP:
                $interaction->deleteFollowUpMessage($pk->getMessageId());
                break;
            case $pk::UPDATE_MESSAGE:
                $interaction->updateMessage($builder);
                break;
        }
    }

**Comment by iZeaoGamer** [comment]
I've also added print_r during Button Listener for testing purposes, and it appears the Listener doesn't get called until 2-3 button clicks.

**Comment by iZeaoGamer** [comment]
Does the Button Listener have to be during Ready Event or can you use it elsewhere too?

**Comment by iZeaoGamer** [comment]
So I just realized - It turns out the event its self is fired, but the Button->setListener() callable isn't. Sorry for the confusion.

**Comment by iZeaoGamer** [comment]
Nvm I fixed the bug
