### ISSUE TITLE
PresenceUpdate guild attribute

### ISSUE THREAD

**Issue by xWildFire** [discord-php/DiscordPHP#757]
**Environment**
- PHP Version:
    - 8.0.10
- DiscordPHP Version:
    - 7.0.0

**Describe the bug**

`[2022-03-07 13:56:51] Message: Discord\Parts\WebSockets\PresenceUpdate::getGuildAttribute(): Return value must be of type Discord\Parts\Guild\Guild, null returned
	File: /home/wildcord/wildcord/vendor/team-reflex/discord-php/src/Discord/Parts/WebSockets/PresenceUpdate.php:74
	Trace:
		#0 /home/wildcord/wildcord/vendor/team-reflex/discord-php/src/Discord/Parts/Part.php(225): Discord\Parts\WebSockets\PresenceUpdate->getGuildAttribute()
#1 /home/wildcord/wildcord/vendor/team-reflex/discord-php/src/Discord/Parts/Part.php(453): Discord\Parts\Part->getAttribute()
#2 /home/wildcord/wildcord/vendor/team-reflex/discord-php/src/Discord/WebSockets/Events/PresenceUpdate.php(33): Discord\Parts\Part->__get()
#3 /home/wildcord/wildcord/vendor/team-reflex/discord-php/src/Discord/Discord.php(736): Discord\WebSockets\Events\PresenceUpdate->handle()
#4 /home/wildcord/wildcord/vendor/team-reflex/discord-php/src/Discord/Discord.php(601): Discord\Discord->handleDispatch()
#5 /home/wildcord/wildcord/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Discord\Discord->handleWsMessage()
#6 /home/wildcord/wildcord/vendor/ratchet/pawl/src/WebSocket.php(72): Ratchet\Client\WebSocket->emit()
#7 /home/wildcord/wildcord/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(248): Ratchet\Client\WebSocket->Ratchet\Client\{closure}()
#8 /home/wildcord/wildcord/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(194): Ratchet\RFC6455\Messaging\MessageBuffer->processData()
#9 /home/wildcord/wildcord/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Ratchet\RFC6455\Messaging\MessageBuffer->onData()
#10 /home/wildcord/wildcord/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit()
#11 /home/wildcord/wildcord/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}()
#12 /home/wildcord/wildcord/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit()
#13 /home/wildcord/wildcord/vendor/react/event-loop/src/StreamSelectLoop.php(245): React\Stream\DuplexResourceStream->handleData()
#14 /home/wildcord/wildcord/vendor/react/event-loop/src/StreamSelectLoop.php(212): React\EventLoop\StreamSelectLoop->waitForStreamActivity()
#15 /home/wildcord/wildcord/src/WildCord/App.php(435): React\EventLoop\StreamSelectLoop->run()
#16 /home/wildcord/wildcord/bot.php(10): WildCord\App->run()
#17 {main}`

**To Reproduce**
No idea, my bot is working 24/7 on many servers and crashes with this error 3rd time.

**Comment by SQKo** [comment]
Please try on latest `dev-master`

**Comment by xWildFire** [comment]
Now its fine.
