### ISSUE TITLE
An error with voice channels

### ISSUE THREAD

**Issue by Laith98Dev** [discord-php/DiscordPHP#766]
I have a problem, sometimes the server closed with error:
`AssertionError: "Voice Channel for leaving member '935680500058710016.741048650947493950' not found in storage." (EXCEPTION) in "plugins/DiscordBot.phar/src/Plugin/BotCommunicationHandler" at line 154`

**Environment**
- PHP Version:
    - v8.0.16
- DiscordPHP Version:
    - v2.1.1

**Comment by davidcole1340** [comment]
Error doesn't come from library, see https://github.com/DiscordBot-PMMP/DiscordBot/issues/54
