### ISSUE TITLE
Undefined done method on member getPermission

### ISSUE THREAD

**Issue by anggi117** [discord-php/DiscordPHP#767]
Hii, im using $member->getPermission on messageReaction

but after im using messageReaction class with member property, get some error notification undefined done method

this my code and with error too
![image](https://user-images.githubusercontent.com/42998655/159650478-978a4bc0-b88c-4d9b-ad0a-73bf1513537a.png)

**Comment by SQKo** [comment]
`getPermissions()` is not a promise, the permission is returned directly

```php
$permission = $reaction->member->getPermissions($reaction->channel);
```

**Comment by anggi117** [comment]
> `getPermissions()` is not a promise, the permission is returned directly
> 
> ```
> $permission = $reaction->member->getPermissions($reaction->channel);
> ```

thanks mann
