### ISSUE TITLE
Is there possible for get data from DiscordPHP.Debug ?

### ISSUE THREAD

**Issue by anggi117** [discord-php/DiscordPHP#770]
Is possible for get data from this ? i screenshot that after running DiscordPHP Service

![image](https://user-images.githubusercontent.com/42998655/160572332-6626f4cf-f886-4b0f-bf6a-b63f715a3e6b.png)

**Comment by key2peace** [comment]
`	require_once(__DIR__.'/vendor/autoload.php');

	use Discord\Discord;
	use Monolog\Handler\StreamHandler;
	use Monolog\Logger;

	$logger = new Logger('DiscordPHP');
	$logger->pushHandler(new StreamHandler(__DIR__ . '/bot.log', Logger::DEBUG));

	$discord = new Discord([
		'token' => 'yourtoken',
		'logger' => $logger,
	]);
`

**Comment by SQKo** [comment]
Some of those data are available under `ready` event
```php
$discord->on('ready', function ($discord) {
    $discord->username;
    $discord->discriminator;
    $discord->avatar;
    $discord->mfa_enabled;
    $discord->verified;
    $discord->email;
});
```

**Comment by anggi117** [comment]
> Some of those data are available under `ready` event
> 
> ```
> $discord->on('ready', function ($discord) {
>     $discord->username;
>     $discord->discriminator;
>     $discord->avatar;
>     $discord->mfa_enabled;
>     $discord->verified;
>     $discord->email;
> });
> ```

Thankss solved
