### ISSUE TITLE
Private messages to bot cause undefined property error

### ISSUE THREAD

**Issue by Shinidoki** [discord-php/DiscordPHP#776]
When direct messaging the bot, I currently receive an undefined property error:

> Undefined property: Discord\Parts\Channel\Message::$channel in vendor/team-reflex/discord-php/src/Discord/Parts/Channel/Message.php:366
> Stack trace:
> 0 vendor/team-reflex/discord-php/src/Discord/Parts/Channel/Message.php(366): yii\base\ErrorHandler->handleError()
> 1 vendor/team-reflex/discord-php/src/Discord/Parts/Part.php(225): Discord\Parts\Channel\Message->getGuildAttribute()
> 2 vendor/team-reflex/discord-php/src/Discord/Parts/Part.php(453): Discord\Parts\Part->getAttribute()
> 3 vendor/team-reflex/discord-php/src/Discord/Parts/Channel/Message.php(319): Discord\Parts\Part->__get()
> 4 vendor/team-reflex/discord-php/src/Discord/Parts/Part.php(225): Discord\Parts\Channel\Message->getChannelAttribute()
> 5 vendor/team-reflex/discord-php/src/Discord/Parts/Part.php(453): Discord\Parts\Part->getAttribute()
> 6 vendor/team-reflex/discord-php/src/Discord/WebSockets/Events/MessageCreate.php(33): Discord\Parts\Part->__get()
> 7 vendor/team-reflex/discord-php/src/Discord/Discord.php(738): Discord\WebSockets\Events\MessageCreate->handle()
> 8 vendor/team-reflex/discord-php/src/Discord/Discord.php(603): Discord\Discord->handleDispatch()
> 9 vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Discord\Discord->handleWsMessage()
> 10 vendor/ratchet/pawl/src/WebSocket.php(72): Ratchet\Client\WebSocket->emit()
> 11 vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(248): Ratchet\Client\WebSocket->Ratchet\Client\{closure}()
> 12 vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(194): Ratchet\RFC6455\Messaging\MessageBuffer->processData()
> 13 vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Ratchet\RFC6455\Messaging\MessageBuffer->onData()
> 14 vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit()
> 15 vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}()
> 16 vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit()
> 17 vendor/react/event-loop/src/ExtUvLoop.php(310): React\Stream\DuplexResourceStream->handleData()
> 18 [internal function]: React\EventLoop\ExtUvLoop->React\EventLoop\{closure}()
> 19 vendor/react/event-loop/src/ExtUvLoop.php(232): uv_run()
> 20 vendor/team-reflex/discord-php/src/Discord/Discord.php(1390): React\EventLoop\ExtUvLoop->run()
> 21 BotController.php(82): Discord\Discord->run()

I use the following code to listen to 'MESSAGE_CREATE':
```
$discord->on(Event::MESSAGE_CREATE, function (Message $message, Discord $discord) {
    echo 'Message received: ' . $message->member->username . ' - ' . $message->content . "\r\n";
});
```

It used to work some time ago.
I updated to the most recent version v7.0.7

**Comment by SQKo** [comment]
Please update again to 7.0.8
