### ISSUE TITLE
How to put emoji on embed fields value

### ISSUE THREAD

**Issue by anggi117** [discord-php/DiscordPHP#777]
Is this possible for put emoji from external server to embed ?

**Comment by SQKo** [comment]
As embed field value, as long your bot is also in that external server where the emoji comes from, and your bot has permission to use external emoji in your server, just pass the string using the emoji format `<:name:emoji_id>`

https://discord.com/developers/docs/reference#message-formatting-formats

**Comment by anggi117** [comment]
> As embed field value, as long your bot is also in that external server where the emoji comes from, and your bot has permission to use external emoji in your server, just pass the string using the emoji format `<:name:emoji_id>`
> 
> https://discord.com/developers/docs/reference#message-formatting-formats

Thankss solved
