### ISSUE TITLE
is this possible for not using "value" on embed fields ?

### ISSUE THREAD

**Issue by anggi117** [discord-php/DiscordPHP#779]
Is this possible for not using "value" on embed fields ?

if im using like this : 
`'1' => array(
                    'name' => 'Rarity',
                    "value" => "\u{200b}"
                )`

they will make 1 breakline like this 
![image](https://user-images.githubusercontent.com/42998655/160972135-dfd39465-08ac-49c8-9b04-8faf41de2815.png)

i just want delete that breakline. Thanksss

**Comment by key2peace** [comment]
no, this is not possible as [per documentation](https://discord.com/developers/docs/resources/channel#embed-object-embed-field-structure)
