### ISSUE TITLE
Remove url embeds after reply

### ISSUE THREAD

**Issue by MichaelBelgium** [discord-php/DiscordPHP#785]
How exactly to do this?

I've tried doing

```
$message->reply($text)->always(function (Message $m) {
    $m->embeds->clear();
});
```

but nothing happens. Even doing a dump or anything in the always() (or done(), then()) callback it doesn't  get called? What am i missing?

**Comment by key2peace** [comment]
this would only remove the embeds in local memory, you would need to edit the message with the new content in order to display the change on discord itself. also note that $m is the newly by the reply generated message, not sure if that what you want.

**Comment by MichaelBelgium** [comment]
>  If your goal is to PREVENT embeds being added based on the urls, use <url> instead.

Yes it is, what do you mean with <url>? Place the url between brackets?
