### ISSUE TITLE
No FFmpeg binary was found  but i have it installed.

### ISSUE THREAD

**Issue by Lucasnl** [discord-php/DiscordPHP#790]
when i use ffmpeg -version  , it says version 5.0.1
![image](https://user-images.githubusercontent.com/41349947/164987637-82fad2f3-26e8-40f0-9960-606f2b41e6aa.png)

but when i try to use a music bot , it returns that i don't have ffmpeg installed but it was working perfectly yesterday
i dont know what else i can do to be honest.
![image](https://user-images.githubusercontent.com/41349947/164987600-7081b5a7-d323-4f67-83aa-e31d9bfde71b.png)

**Comment by exussum12** [comment]
The command is running `where ffmpeg`
I assume that fails ?

**Comment by SQKo** [comment]
Try in latest master 59b45a9 branch
