### ISSUE TITLE
Interaction object cannot be fully restored

### ISSUE THREAD

**Issue by Swift42** [discord-php/DiscordPHP#794]
**Environment**
- PHP Version:
    - 8.0
- DiscordPHP Version:
    - latest dev

**Describe the bug**
With the old slash library it was possible to store an Interaction object (Discord\Slash\Parts\Interaction) in a json, restore it later (even after a bot restart) and change the original message with "updateInitialResponse":
```
$data=json_encode($interaction->jsonSerialize());
[...]
$interaction=new Interaction(json_decode($data),$discord);
$interaction->updateInitialResponse(...);
```
After I removed the slash library and switched to the new native commands, the object can still be restored:
```
$data=json_encode($interaction->getRawAttributes());
[...]
$interaction=new Interaction($discord,json_decode($data,TRUE));
$interaction->updateOriginalResponse(...);
```
But with one big problem: The native Interaction class has the internal variable "responded". This variable isn't set through the attributes and there is no way to set this variable from outside (because it's protected and has no setter).
But to use "updateOriginalResponse" with the restored object the variable "responded" must be "true", otherwise the posting won't update.

For a quick fix I added this to Discord/Parts/Interactions/Interaction.php:
```
    public function setResponded()
    {
        $this->responded=true;
    }
```
When I use $interaction->setResponded() after the restore of the Interaction object, now everything works as expected.
But an "official" way to do this would be nice. 
Thanks for your support.

**Comment by SQKo** [comment]
DiscordPHP-Slash does not support DiscordPHP v7.0 or dev-master.

Once you migrate to DiscordPHP 7.0 you are not supposed to create the Interaction class manually, then the responded variable will behave normally. If we add the set for this, someone else could just get Interaction error later.

**Comment by Swift42** [comment]
But how can I then restore an Interaction object after a bot restart?
Example: I have a long running process and after the process is done, the Interaction message should be updated.
But when the bot restarts for some reason in the meantime, there must be a way to reuse the old Interaction again..?
How do I do this when I cannot set the field "responded"?

**Comment by SQKo** [comment]
There is no correct way to tell if interaction is still valid after bot restart in gateway, because it also expires in 15 minutes. You should invalidate that old interaction data and just edit the message with new MessageBuilder of same message

**Comment by SQKo** [comment]
I will try research if `getOriginalResponse()` and `getFollowUpMessage()` can be used to determine if interaction was already responded, but you have to set your Interaction Part `created` parameter to true and call one of the two function above before going for `updateOriginalResponse()`

**Comment by SQKo** [comment]
Try branch `[interaction-responded](https://github.com/discord-php/DiscordPHP/tree/interaction-responded)` branch first

You will have to call either `getOriginalMessage()` or `getFollowUpMessage()` before using the respond functions

**Comment by Swift42** [comment]
Wohoo! This works with the patch:
```
// saving the original interaction data in a json:
$jsondata=json_encode($interaction->getRawAttributes());
[...]
// after bot restart:
$interaction=new Interaction($discord,json_decode($jsondata,TRUE),true);
$interaction->getOriginalResponse()->done(function(Message $message) use ($interaction)
{
	$interaction->updateOriginalResponse(MessageBuilder::new()->setContent('New content'));				
});
```
Thank you very much!
