### ISSUE TITLE
Bad Request - { "message": "Cannot send an empty message", "code": 50006 }

### ISSUE THREAD

**Issue by heyitsmarlon** [discord-php/DiscordPHP#797]
My application was built using DiscordPHP last year and it worked perfectly up until just recently. No changes have been made to the code but since a few days I get the error `Bad Request - { "message": "Cannot send an empty message", "code": 50006 }`.

What could possibly be the issue?

**Comment by iZeaoGamer** [comment]
This is more likely due to the message content and embedding becoming empty, regardless if you haven't modified anything.

**Comment by key2peace** [comment]
what are you trying there? show code example please...
