### ISSUE TITLE
Can't add roles to user

### ISSUE THREAD

**Issue by Kendaluski** [discord-php/DiscordPHP#802]
I can't add roles to any users, i get an error that sais: "Call to a member function addRole() on null". 
Here is my code:

![image](https://user-images.githubusercontent.com/105867025/169309661-842b0a68-c3da-4440-a065-2c78c75f8f21.png)

**Comment by key2peace** [comment]
use ``$message->member`` instead of ``$message->author->member``

**Comment by Kendaluski** [comment]
Thank you so much, it worked!!!
