### ISSUE TITLE
How to cancel delayed reply ?

### ISSUE THREAD

**Issue by anggi117** [discord-php/DiscordPHP#803]
Is there any solution for cancel delayed reply ?

**Comment by SQKo** [comment]
Not possible yet, create your own timer code to prepare reply and cancel it

**Comment by anggi117** [comment]
> Not possible yet, create your own timer code to prepare reply and cancel it

its possible for using $loop->stop(); ?
if possible how to use that

**Comment by SQKo** [comment]
> its possible for using $loop->stop(); ? if possible how to use that
No, doing so will stop the bot

You have to create your own timer for a delayed reply

```php
// take loop
$loop = $discord->getLoop();

// start timer
$timer = $loop->addTimer(time in seconds, function () use ($message) {
    $message->reply('reply here...')->done(...);
});

// to cancel
$loop->cancelTimer($timer);
```

**Comment by anggi117** [comment]
> > its possible for using $loop->stop(); ? if possible how to use that
> > No, doing so will stop the bot
> 
> You have to create your own timer for a delayed reply
> 
> ```
> // take loop
> $loop = $discord->getLoop();
> 
> // start timer
> $timer = $loop->addTimer(delay time in seconds, function () use ($message) {
>     // send reply when delay time is reached
>     $message->reply('reply here...')->done(...);
> });
> 
> // to cancel
> $loop->cancelTimer($timer);
> ```

but if im using $timer variable, how to im run it if i dont wan't cancel it ?

**Comment by SQKo** [comment]
> but if im using $timer variable, how to im run it if i dont wan't cancel it ?

then dont do $loop->cancelTimer(...)

**Comment by anggi117** [comment]
> > but if im using $timer variable, how to im run it if i dont wan't cancel it ?
> 
> then don't do `$loop->cancelTimer(...)`

how to using cancelTimer if im using "if statement"
i try like this 
`if($message->content == "showtime") {
            $timer = $loop->addTimer(4, function () use($message) {
                    $message->reply('test')->done();
                });

        }
        if($message->content == "stop") {
            $loop->cancelTimer($timer);
        }`
        
        but yeah this failed
