### ISSUE TITLE
How to join voice channel?

### ISSUE THREAD

**Issue by kienngoctrinh** [discord-php/DiscordPHP#804]
I cant join voice channel

**Comment by SQKo** [comment]
Can you show the code and the error please?

**Comment by kienngoctrinh** [comment]
> Can you show the code and the error please?

Yep!

$discord->on('message', function (Message $message, Discord $discord) {

    if ($message->author->bot) {
        return;
    }

    if ($message->content == '!bot') {
        $discord->joinVoiceChannel(1, false, true, null, true);
    }

})

**Comment by SQKo** [comment]
What is `1`? that should be a Voice channel object

**Comment by kienngoctrinh** [comment]
1 is name voice channel on discord

**Comment by SQKo** [comment]
You have to get the channel first..

```php
$voicechan = $message->guild->channels->get('name', '1');
$discord->joinVoiceChannel($voicechan, false, true, null, true);
```

But if that does not work, you must fetch the channel first using the channel ID.
Enable developer mode in your discord client, right click on the voice channel, and select "Copy ID"

```php
$message->guild->channels->fetch('id', 'channel id here')->done(function ($voicechan) use ($discord) {
    $discord->joinVoiceChannel($voicechan, false, true, null, true);
});
```

**Comment by kienngoctrinh** [comment]
$message->guild->channels->fetch('paste channel id here')->done(function ($voicechan) use ($discord) {
    $discord->joinVoiceChannel($voicechan, false, true, null, true);
});

Like this works.
Is there any way to get auto id when joining voice channel.

**Comment by SQKo** [comment]
There is no "auto id", so I don't know what you mean with that.

If you mean to automatically pick a voice channel in the guild, then you can filter:
```php
$anyVoiceChan = $message->guild->channels->filter(function ($channel) {
    return $channel->allowVoice();
});

if ($anyVoiceChan) { 
    $discord->joinVoiceChannel($anyVoiceChan, false, true, null, true);
} else {
    // no voice channel found
}
```
