### ISSUE TITLE
how to reply with a DM instead of replying in the channel

### ISSUE THREAD

**Issue by m00nm00nm00n** [discord-php/DiscordPHP#808]
Hi,

How can I reply to a user's command with a direct message rather than in the channel?

I'd like a user to type a command in the channel, but then receive the response as a DM. 

How can I accomplish this? I am able to pull the author id

    $discord->on('message', function ($message, $discord) {
    $author = $message->author;
    $author_id = $author->id;

what function do I need to use to send a DM to the user?

**Comment by SQKo** [comment]
```php
$message->user->sendMessage(...);
```
