### ISSUE TITLE
Support for zlib-stream compression

### ISSUE THREAD

**Issue by neshala** [discord-php/DiscordPHP#810]
The official Discord websocket link from the browser is done using zlib-stream compression:

`wss://gateway.discord.gg/?encoding=json&v=9&compress=zlib-stream`

I think that this package does not have support for  zlib-stream compression and works just with uncompressed data.
It was fine for me until I realized that messages from the servers of 300k+ users are not delivered (or very rearly) to the bot so maybe it's because there is no compression enabled.

Is it possible to enable it now, or is that feature not yet supported, and is there any plan to add that in the future?

**Comment by SQKo** [comment]
Not possible now, will require extra library https://github.com/clue/reactphp-zlib and probably will add it in future as optional

**Comment by neshala** [comment]
Thanks a lot for the provided library, I was able to test it and it works perfectly with discord zlib-stream compression.
The only important is to switch default compression to ZLIB_ENCODING_DEFLATE , that's the one Discord team is using.
