### ISSUE TITLE
How to get user status?

### ISSUE THREAD

**Issue by stankarp** [discord-php/DiscordPHP#813]
Hi,
How can I get user status (online, idle, etc.)? The only way I figured is through PRESENCE_UPDATE event, but I need to know user status(es) right after server started, don't want to wait when PRESENCE_UPDATE fired :\

**Comment by SQKo** [comment]
The `PRESENCE_UPDATE` is automatically fired after connect if you have `GUILD_MEMBERS` intent and `loadAllMembers` enabled

**Comment by stankarp** [comment]
Thanks!
