### ISSUE TITLE
Short audio files will not be heard after the second playback

### ISSUE THREAD

**Issue by Nerahikada** [discord-php/DiscordPHP#814]
**Environment**
- PHP Version:
    - 8.1.5
- DiscordPHP Version:
    - dev-master (b39dfd7ed6887226be638c94f5c9c28cd822bc82)

**Describe the bug**
I am experiencing the same problem as #444.
When audio files of about 3 seconds are played in succession, the audio will be inaudible after the second time.

**To Reproduce**
```php
<?php

require_once 'vendor/autoload.php';

use Discord\Discord;
use Discord\Parts\WebSockets\VoiceStateUpdate;
use Discord\Voice\VoiceClient;
use Discord\WebSockets\Event;

$discord = new Discord(['token' => '']);
$discord->on(Event::VOICE_STATE_UPDATE, function(VoiceStateUpdate $state, Discord $discord){
	$discord->joinVoiceChannel($discord->getChannel($state->channel_id))->then(function(VoiceClient $voice){
		$voice->playFile('test.wav')->then(fn() => $voice->playFile('test.wav'));
	});
});
$discord->run();
```

**Expected behavior**
The audio should still be audible the second time around.

**Additional context**
Audio file used for the test: http://soundbible.com/2098-Grim-Reaper-Your-Soul.html

**Comment by key2peace** [comment]
which operating system are you using?

**Comment by Nerahikada** [comment]
I was able to reproduce this on both Windows 10 and Ubuntu 20.04 (wsl)

**Comment by key2peace** [comment]
can you try again with latest dev-master?

**Comment by Nerahikada** [comment]
I updated to `980113231d53ba6cd5fdec944a3219d7ef8f66b0` but it does not seem to be improving

**Comment by davidcole1340** [comment]
> I updated to [9801132](https://github.com/discord-php/DiscordPHP/commit/980113231d53ba6cd5fdec944a3219d7ef8f66b0) but it does not seem to be improving

could you please test with `dev-fix/audio_series` -- playing the audio provided seems to work with these changes

**Comment by Nerahikada** [comment]
The issue has been fixed in that branch
