### ISSUE TITLE
Text field not sent. Throws an API error.

### ISSUE THREAD

**Issue by robotateme** [discord-php/DiscordPHP#828]
`$input = TextInput::new("Email", 2, '_email')
                            ->setRequired(true)
                            ->setPlaceholder('user@joy-dev.com')
                            ->setMinLength(3)
                            ->setMaxLength(30)
                            ->setValue('email@joy-dev.com')
                        ;

                        $actionRow = ActionRow::new()
                            ->addComponent($input)
                            ->addComponent(Button::new(Button::STYLE_SUCCESS)->setLabel('Ok'))
                            ->addComponent(Button::new(Button::STYLE_DANGER)->setLabel('Cancel'))
                        ;

                        $select = SelectMenu::new()
                            ->addOption(Option::new('me?'))
                            ->addOption(Option::new('or me?'));

                        $messageBuilder
                            ->addComponent($select)
                            ->addComponent($actionRow)
                            ->setContent('Hello!');

                        $message->channel->sendMessage($messageBuilder);`

`{
    "code": 50035,
    "errors": {
        "components": {
            "0": {
                "components": {
                    "0": {
                        "_errors": [
                            {
                                "code": "COMPONENT_TYPE_INVALID",
                                "message": "The specified component type is invalid in this context"
                            }
                        ]
                    }
                }
            }
        }
    },
    "message": "Invalid Form Body"
}`

**Comment by SQKo** [comment]
You can only use TextInput in a modal, not text messages.

**Comment by SQKo** [comment]
modal can be only triggered from an interaction, thus you need to do it from message components (e.g. buttons, select menus) listener or applicatiln command (e.g. slash, user, message context menu) listeners by using `$interaction->showModal()`

Example:
```php
$ar = ActionRow::new();
$ti = TextInput::new('A Text input here', TextInput::STYLE_SHORT, 'first');
$ar->addComponent($ti);
$ar2 = ActionRow::new();
$ti2 = TextInput::new('Another Text input here', TextInput::STYLE_PARAGRAPH, 'second');
$ar2->addComponent($ti2);
$customId = '123';
$interaction->showModal('A modal title', $customId, [$ar, $ar2], function (Interaction $interaction, Collection $components) {
    var_dump($components);
    // $components['first']->value
    // $components['second']->value
    $interaction->acknowledge();
});
```

Please note that right now modal only support TextInput, no SelectMenu nor Buttons yet

**Comment by robotateme** [comment]
> modal can be only triggered from an interaction, thus you need to do it from message components (e.g. buttons, select menus) listener or application command (e.g. slash, user, message context menu) listeners by using `$interaction->showModal()`
> 
> Example:
> 
> ```
> $ar = ActionRow::new();
> $ti = TextInput::new('A Text input here', TextInput::STYLE_SHORT, 'first');
> $ar->addComponent($ti);
> $ar2 = ActionRow::new();
> $ti2 = TextInput::new('Another Text input here', TextInput::STYLE_PARAGRAPH, 'second');
> $ar2->addComponent($ti2);
> $customId = '123';
> $interaction->showModal('A modal title', $customId, [$ar, $ar2], function (Interaction $interaction, Collection $components) {
>     var_dump($components);
>     // $components['first']->value
>     // $components['second']->value
>     $interaction->acknowledge();
> });
> ```
> 
> Please note that right now modal only support TextInput, no SelectMenu nor Buttons yet

OK. Thank you.
