### ISSUE TITLE
VoiceClient: arm64/aarch64 support

### ISSUE THREAD

**Issue by Nerahikada** [discord-php/DiscordPHP#837]
**Is your feature request related to a problem? Please describe.**
The voice client does not work on ARM64 architecture.

**Describe the solution you'd like**
Please support voice clients on ARM64 architecture.

**Comment by SQKo** [comment]
If you know how, you can try build one from https://github.com/davidcole1340/dca

**Comment by key2peace** [comment]
With the upcoming PR #962 , dca will no longer be required

**Comment by key2peace** [comment]
#962 has been merged, please try again

**Comment by Nerahikada** [comment]
It works! thank you <3
