### ISSUE TITLE
Undefined variable: user

### ISSUE THREAD

**Issue by wohahobg** [discord-php/DiscordPHP#851]
I just update to lasted version of DiscordPHP and it's look like there is misstype for variable in 
**Repository/Guild/BanRepository.php**  https://github.com/discord-php/DiscordPHP/tree/master/src/Discord/Repository/Guild over here you can see it aswell it should be $member instant of $user it is on line 108 
```
        if ($user instanceof User || $user instanceof Member) {

```

**Comment by SQKo** [comment]
soz my mistake when resolving conflicted PR, will be fixed asap

**Comment by SQKo** [comment]
Try update [v7.1.1](https://github.com/discord-php/DiscordPHP/releases/tag/v7.1.1)
