### ISSUE TITLE
How to use Embed?

### ISSUE THREAD

**Issue by oidominguez** [discord-php/DiscordPHP#853]
I'm using this method to respond to commands:

> $interaction->respondWithMessage(MessageBuilder::new()->setContent('Ready!'));

How can I switch to an embed with:
- Title;
- Color;
- Image;
- Contents;
- Footer.

Thank you for your attention and any way you can try to help!

**Comment by SQKo** [comment]
```php
$builder = MessageBuilder::new();
$builder->setContent('Ready!');

$embed = new Embed($discord, [
    'title' => 'Embed title',
    'color' => -1,
    // ...
]);

// Or add attributes using methods
$embed->setTitle(...);
$embed->setColor(...);
// ...

$builder->addEmbed($embed);
 
$interaction->respondWithMessage($embed);
```
