### ISSUE TITLE
Add support for creating scheduled events.

### ISSUE THREAD

**Issue by halid96** [discord-php/DiscordPHP#883]

**Comment by SQKo** [comment]
Already exists...
```php
$scheduledEvent = new ScheduledEvent($discord, [...]);

$guild->scheduled_events->save->($scheduledEvent);
```

**Comment by halid96** [comment]
> Already exists...
> 
> ```
> $scheduledEvent = new ScheduledEvent($discord, [...]);
> 
> $guild->guild_scheduled_events->save($scheduledEvent);
> ```

But how to use this code? There is no proper documentation.

**Comment by key2peace** [comment]
Looking for https://discord.com/developers/docs/resources/guild-scheduled-event#create-guild-scheduled-event ?

**Comment by halid96** [comment]
> Looking for https://discord.com/developers/docs/resources/guild-scheduled-event#create-guild-scheduled-event ?

Yes. I used the Discord API. But I wanted to do it using this library. That's OK, thank you for the info.

**Comment by key2peace** [comment]
well, what I mean with that link is that it shows you what array you need to place in ``$scheduledEvent = new ScheduledEvent($discord, [<here>]);``
