### ISSUE TITLE
How to attach a filename (not url) to an embed (and not to the message)?

### ISSUE THREAD

**Issue by Swift42** [discord-php/DiscordPHP#891]
I know I can add a file to the MessageBuilder with ->addFile($filename,basename($filename));
But this doesn't add the image to the embed, it adds the image to the message and this is not the same.

According to the official docs this can be solved by using an Attachment in an embed: https://discordjs.guide/popular-topics/embeds.html#attaching-images

I found the undocumented class Discord/Parts/Channel/Attachment, but I failed to use it.
Can you please give an example how to load an embed image (e.g. image.jpg) from the disk instead from an URL, so I can e.g. use:
$embed[ 'image']['url']='attachment://image.jpg';

Thanks in advance.

**Comment by SQKo** [comment]
```php
$embed->setImage("file://$filename");
```

**Comment by Swift42** [comment]
The official Discord API docs state the same:
https://discord.com/developers/docs/resources/channel#embed-object-embed-image-structure

> url: source url of image (only supports http(s) and **attachments**)

So somehow an attachment should be possible ... ?

**Comment by SQKo** [comment]
> The official Discord API docs state the same: https://discord.com/developers/docs/resources/channel#embed-object-embed-image-structure
> 
> > url: source url of image (only supports http(s) and **attachments**)
> 
> So somehow an attachment should be possible ... ?

I think you are confused, you add image from disk with MessageBuilder addFile, then you "attach" the image to embed using setImage with the attachment://filename link

**Comment by Swift42** [comment]
> I think you are confused

haha, this might be :-)
But thanks for pointing me in the right direction, it was easier than I thought. 
For future reference, this seems to work:

[ declaring the embed data, then finally: ]
$useimg='/path/to/img.jpg';
$embed['image']['url']='attachment://'.basename($useimg);
$messagebuilder = MessageBuilder::new()
->addEmbed($embed)
->addFile($useimg, basename($useimg));

♥
