### ISSUE TITLE
How can I get the string that the bot gets from sub-command options?

### ISSUE THREAD

**Issue by Vxschlxfner** [discord-php/DiscordPHP#898]
`    $embedcommand = new Command($discord, [
        'name' => 'embed',
        'description' => 'Create an Embed',
        'default_permission' => true,
        'options' => [
            new Option($discord, [
                'name' => 'channel',
                'description' => 'penis',
                'required' => true,
                'type' => Option::CHANNEL,
            ]),
            new Option($discord, [
                'name' => 'nachricht',
                'description' => 'penis',
                'required' => true,
                'type' => Option::STRING,
            ])
        ]
    ]);`
    
    
![image](https://user-images.githubusercontent.com/57720717/186553331-5ef6871e-9141-4895-b51a-3c55766a1b28.png)

**Comment by SQKo** [comment]
### Channel
Get the id: 
`$channelId = $interaction->data->options['channel']->value`

Get the channel:
`$interaction->resolved->channels[$channelId]`


### nachricht
`$interaction->data->options['nachricht']->value`

**Comment by Vxschlxfner** [comment]
> ### Channel
> Get the channel input: `$channelInput= $interaction->data->options['channel']->value`
> 
> Get the channel by name: `$interaction->resolved->channels->get('name', $channelInput)`
> 
> ### nachricht
> `$interaction->data->options['nachricht']->value`

Thank you :)

**Comment by Vxschlxfner** [comment]
PHP Warning:  Undefined property: Discord\Repository\Guild\ChannelRepository::$get in C:\Users\wbloo\Documents\Management-Bot\Management-Bot\main.php on line 103

Code:
`    $channelInput= $interaction->data->options['channel']->value;

    $channel1 = $interaction->resolved->channels->get('name', $channelInput);

    $channel1->sendMessage("Test");`

@SQKo

**Comment by SQKo** [comment]
Sorry, I mistaken it is channel Id

```php
$channelId = $interaction->data->options['channel']->value;

$channel1 = $interaction->data->resolved->channels->get('id', $channelId);
```

**Comment by Vxschlxfner** [comment]
> Sorry, I mistaken it is channel Id
> 
> ```
> $channelId = $interaction->data->options['channel']->value;
> 
> $channel1 = $interaction->data->resolved->channels->get('id', $channelId);
> ```

It works now, Thank you. 

But do you know why discord doesn't want to add these?

![image](https://user-images.githubusercontent.com/57720717/186923823-e7753da0-da19-44cc-9601-f9f8e30b0211.png)

![image](https://user-images.githubusercontent.com/57720717/186923913-3ab02f6f-730c-46d5-83b3-1c5e366a12ae.png)

**Comment by SQKo** [comment]
Check the error logs
I think that your command option name cannot have parenthesis as you used there "color(rgb)"

**Comment by Vxschlxfner** [comment]
> Check the error logs I think that your command option name cannot have parenthesis as you used there "color(rgb)"

There is no error, but I can change it

**Comment by Vxschlxfner** [comment]
![image](https://user-images.githubusercontent.com/57720717/186926013-bf78b95c-3859-42a6-a4d3-05a69681c05f.png)

Yeah, okay, he doesn't want me to put () in there... Thank you for your help :)
