### ISSUE TITLE
Content message is returning empty

### ISSUE THREAD

**Issue by osgyn** [discord-php/DiscordPHP#905]
**Environment**
- PHP Version:
    - 8.1.5
- DiscordPHP Version:
    - 7.2.6

**Describe the bug**
After ~11:50 UTC all my messages is returning with content empty

**To Reproduce**
```php
$discord->on('ready', function ($discord) {
    echo 'Bot is ready!' . PHP_EOL;
    $discord->on('message', function ($message, $discord) {
        var_dump($message->content);
    });
});
```
Response: string(0) ""

**Expected behavior**
Content message

**Additional context**
The problem started today, before that my bot was running normally with ~2 months of uptime.

**Comment by osgyn** [comment]
I've found out.

Discord updated intents so I needed to generate authorization again with new permission "message content intent"

https://stackoverflow.com/a/73037243

**Comment by SQKo** [comment]
For any verified Bots that do not have Message Content intent approved, please use version `dev-master@7702c55` to use the v10 API. Please note this is not a stable release version, and already have some breaking change content with the removal of fields/constants.
