### ISSUE TITLE
Getting empty $message->content as of 2022 Sep 1 ~21:00 UTC

### ISSUE THREAD

**Issue by gcarreno** [discord-php/DiscordPHP#906]
**Environment**
- PHP Version:
    - 8.1.x
- DiscordPHP Version:
    - 7.2.6
    - dev-master

**Describe the bug**
Getting empty string when accessing `$message->content`

**To Reproduce**
From around 2 days ago I decided to update my bot.
Tried dev-master(composer) and got an empty string on `$message->content`.
Decided to revert to 7.2.6(composer) and it worked.
As of 2022 Sep 1 ~21:00 UTC, it's now failing to work even in 7.2.6 and `$message->content` is now return an empty string.

**Expected behavior**
Have `$message->content` return the message content.

**Comment by SQKo** [comment]
https://github.com/discord-php/DiscordPHP/issues/905

**Comment by gcarreno** [comment]
Thanks!!

Closing because I was able to get it working again.

Just had to turn on message content intent on the Developer interface and then add `Intents::MESSAGE_CONTENT` to the list of intents.

All good !!
