### ISSUE TITLE
Message class content property not working

### ISSUE THREAD

**Issue by skh6075** [discord-php/DiscordPHP#909]
**Environment**
- PHP Version:
    - 8.0.18
- DiscordPHP Version:
    - 7.3.0

**Describe the bug**
The result value of $message->content is fixed to blank

**To Reproduce**
```php
$discord->on(Event::MESSAGE_CREATE, function (Message $message, Discord $discord) {
	if($message->author->bot){
		return;
	}
	$message->reply("user: {$message->author->username}, message: {$message->content}, engine ver: " . phpversion());
	echo "{$message->author->username}: {$message->content}", PHP_EOL;
});
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/44698603/188630398-f3b20e1e-70d9-405e-b978-9efb400c3cc9.png)
![image](https://user-images.githubusercontent.com/44698603/188630465-dcc50274-7c85-43cb-b7ab-34fbb7cbb38d.png)

**Additional context**

**Comment by SQKo** [comment]
Duplicate: https://github.com/discord-php/DiscordPHP/issues/905

**Comment by key2peace** [comment]
author happy with reply, thus resolved
