### ISSUE TITLE
How can I hide a command from the default help command

### ISSUE THREAD

**Issue by MattMski** [discord-php/DiscordPHP#915]
Hello, is there any way to hide specific commands from the help command so they are not displayed?

**Comment by SQKo** [comment]
I'm not really sure, but you can set the `defaultHelpCommand` in options to `false`, this disable the whole command help

https://github.com/discord-php/DiscordPHP/wiki/Command-Client

**Comment by MattMski** [comment]
Yeah was kind of looking for something to hide it from the help command so the help command can still exist. Thanks.

**Comment by key2peace** [comment]
there is now an option called 'showHelp' available you can use to control this

**Comment by MattMski** [comment]
> there is now an option called 'showHelp' available you can use to control this

Wonderful, great to hear something like this was added so fast. Thank you!
