### ISSUE TITLE
How can I get a count of all channels on all guides

### ISSUE THREAD

**Issue by MattMski** [discord-php/DiscordPHP#917]
Hello, is there any way to get a count of all the channels on all guides.

I am using $discord->private_channels->count() but that does not seem to be working.

**Comment by key2peace** [comment]
```php
$count = 0;
foreach($discord->guilds as $guild)
  $count += $guild->channels->count();
```

**Comment by MattMski** [comment]
Perfect that worked excellent, thank you very much!
