### ISSUE TITLE
How Discord-PHP handles events ?

### ISSUE THREAD

**Issue by halid96** [discord-php/DiscordPHP#931]
```
$discord->on('ready', function ($discord) {
    /* $discord->on(Event::MESSAGE_CREATE, function (Message $message, Discord $discord) {
        
    }); */

    $discord->on(Event::INTERACTION_CREATE, function (Interaction $interaction, Discord $discord) {
    
    });
)};
```
Eg: if I remove the event listener **MESSAGE_CREATE**, Does Discord still sends a message event object to my server?

I only need slash commands... My idea is to save I/O and increase performance by eliminating unnecessary event data.

**Comment by SQKo** [comment]
The `on()` method is from [Evenement](https://github.com/igorw/evenement/tree/master/doc)
If you remove the event listener Discord will still send a message event to your bot

So if you want to save bandwidth, you should disable the events from the options:
```php
$discord = new Discord([
    'token' => '...',
    'disabledEvents' => [
        Event::MESSAGE_CREATE, Event::MESSAGE_DELETE, // etc
    ],
]);
```

**Comment by halid96** [comment]
> The `on()` method is from [Evenement](https://github.com/igorw/evenement/tree/master/doc) If you remove the event listener Discord will still send a message event to your bot
> 
> So if you want to save bandwidth, you should disable the events from the options:
> 
> ```
> $discord = new Discord([
>     'token' => '...',
>     'disabledEvents' => [
>         Event::MESSAGE_CREATE, Event::MESSAGE_DELETE, // etc
>     ],
> ]);
> ```

Oh thank you for the fast response! Do you have `enabledEvents` instead of `disabledEvents` ?

**Comment by SQKo** [comment]
There isn't

You might want to enable intents instead:
https://discord.com/developers/docs/topics/gateway#list-of-intents
Each intent disables a group or two events, but not bound to one kind, if you want to disable all MESSAGE_CREATE you must not enable all intents having MESSAGE_CREATE, use combination of disabledEvents if you want to control that (but still the bot will use the bandwidth).
```php
$discord = new Discord([
    'token' => '...',
    'Intents' => [
        Intents::GUILDS, // enable GUILDS intent
        Intents::GUILD_BANS, // enable GUILD_BANS intent
    ],
]);
```

**Comment by halid96** [comment]
> 

This extra info was useful, thank you so much **SQKo**
