### ISSUE TITLE
$discord->close(); is not working on Linux Ubuntu

### ISSUE THREAD

**Issue by halid96** [discord-php/DiscordPHP#936]
Here is my code, which is running perfectly on Windows by executing the file `php stop.php`... Months ago on Linux was working, but now the BOT stays online... I am pretty sure, i am not running the bot from different devices at the same time.

Here is my code:
```
<?php
use Discord\Discord;

$root =  dirname(dirname(dirname(dirname(dirname(__DIR__)))));
include $root.'/app/php/init.php';

$discord = new Discord([
    'token' => Config::get_config('api_keys', 'trollex_ai_bot_token'),
]);

$discord->on('ready', function ($discord) {
    $discord->close();
});
``` 
Here is the output after I run with sudo perms: `php start.php`: 
![botstop](https://user-images.githubusercontent.com/24207890/192192952-b5a134bb-7cb2-4556-a066-7be69cce8f54.PNG)

**Comment by halid96** [comment]
I managed to stop the bot, by killing the background process... However before couple of months ago, this was possible to stop the bot with `$dicord->close()`

I am not sure if the issue is about Linux Ubuntu or Discord-PHP, cuz on Windows works perfectly.

**Comment by SQKo** [comment]
What are you trying to do? Close after ready? It's not normal.
Also which commit version of `dev-master` are you using?
