### ISSUE TITLE
Can't create a Message with Inputs

### ISSUE THREAD

**Issue by sluther** [discord-php/DiscordPHP#939]
**Environment**
- PHP Version:
    - 8.1.8
- DiscordPHP Version:
    - 7.3.0

**Describe the bug**
When trying to create a message with inputs, I get an error from the Discord API with the following message:

> {
>   "code": 50035,
>   "errors": {
>     "data": {
>       "components": {
>         "1": {
>           "components": {
>             "0": {
>               "_errors": [
>                 {
>                   "code": "UNION_TYPE_CHOICES",
>                   "message": "Value of field \"type\" must be one of (2, 3, 5, 6, 7, 8)."
>                 }
>               ]
>             },
>             "1": {
>               "_errors": [
>                 {
>                   "code": "UNION_TYPE_CHOICES",
>                   "message": "Value of field \"type\" must be one of (2, 3, 5, 6, 7, 8)."
>                 }
>               ]
>             },
>             "2": {
>               "_errors": [
>                 {
>                   "code": "UNION_TYPE_CHOICES",
>                   "message": "Value of field \"type\" must be one of (2, 3, 5, 6, 7, 8)."
>                 }
>               ]
>             }
>           }
>         }
>       }
>     }
>   },
>   "message": "Invalid Form Body"
> }

**To Reproduce**
```php
        $button = Button::new(Button::STYLE_PRIMARY);
        $button->setLabel('Click me!');

        $button->setCustomId(sha1('testing_' . time()));
        $button->setListener(function(Interaction $interaction) use ($discord) {
            $channel = $discord->getChannel($interaction->channel_id);

            $message = MessageBuilder::new()
                ->setContent(
                    sprintf('%s%s%s%s%s%s%s', $interaction->member->displayname, "\r\n",
                       ":one: ", "\r\n", ":two: ", "\r\n", ":three: "
                    )
                );


            $channel->sendMessage($message);
        }, $discord);

        $input1 = TextInput::new('prototype_input_1', TextInput::STYLE_PARAGRAPH, sha1('input_1_' . time()))
            ->setRequired(true)->setPlaceholder('Input 1');
        $input2 = TextInput::new('prototype_input_2', TextInput::STYLE_PARAGRAPH, sha1('input_2_' . time()))
            ->setRequired(true)->setPlaceholder('Input 2');
        $input3 = TextInput::new('prototype_input_3', TextInput::STYLE_PARAGRAPH, sha1('input_3_' . time()))
            ->setRequired(true)->setPlaceholder('Input 3');

        $inputRow = ActionRow::new()
            ->addComponent($input1)
            ->addComponent($input2)
            ->addComponent($input3);


        $buttonRow = ActionRow::new()->addComponent($button);
        $message = MessageBuilder::new()
            ->setContent('Prototyping')
            ->addComponent($buttonRow)
            ->addComponent($inputRow);

        $interaction->respondWithMessage($message);
```

**Expected behavior**
Instead of getting an error, Inputs should be added to the message

**Comment by SQKo** [comment]
Text input is only supported on modals

**Comment by sluther** [comment]
It looks like that's something that isn't currently supported by this library. Am I incorrect? If not, I'd be happy to contribute a PR for that.

Thanks for the help, and thanks for the awesome library. It's a joy to use!

**Comment by SQKo** [comment]
Unfortunately this is not supported from Discord API side, so doesn't matter what library.
