### ISSUE TITLE
Example Request

### ISSUE THREAD

**Issue by RobertGrubb** [discord-php/DiscordPHP#967]
Hey there,

I'm semi-new to discord bots, but was curious is someone could show me a quick pseudo code that gives an example of knowing when the bot is removed from a server. For instance, I'd like to know when the bot is removed so I can make the necessary changes in the database.

I did a quick search to see if I could find any information on it, maybe I'm just not looking for it the correct way? Any help is appreciated, thank you!

**Comment by key2peace** [comment]
Check ``GUILD_DELETE`` event on http://discord-php.github.io/DiscordPHP/#events
