### ISSUE TITLE
Member is not returning anything.

### ISSUE THREAD

**Issue by rssvxoxo** [discord-php/DiscordPHP#968]
`$member = $guild->members->get('id', $interaction['user']->id);`

While $guild returns the entire guild, can't get information related with member. Imported Discord\Parts\User\Member, still not working.
The event I'm trying to get member;

`$discord->on(Event::INTERACTION_CREATE, function (Interaction $interaction, Discord $discord) use ($guild) `

**Comment by key2peace** [comment]
is the bot only in one guild and you made $guild being globally available in your entire script?

**Comment by rssvxoxo** [comment]
Yes

**Comment by SQKo** [comment]
The answer is to use `$interaction->member`
