### ISSUE TITLE
PlayRawStream not working

### ISSUE THREAD

**Issue by GrzegorzWalewski** [discord-php/DiscordPHP#985]
**Environment**
- PHP Version:
    - 8.0(7.4 same problem)
- DiscordPHP Version:
    - dev-master

**Describe the bug**
playRawStream() is not playing any songs, just silence

**To Reproduce**
```php
        $discord->joinVoiceChannel($channel)->then(function (VoiceClient $client) {
            $stream = new ReadableResourceStream(fopen('http://noisefm.ru:8000/play?icy=http','r'));
            $client->playRawStream($stream)->then(function () {
                echo "done\n";
            }, function ($e) {
                echo "failed to play song:\n";
            });
        }, function ($e) {
            echo "failed to join voice channel:\n";
        });
```

**Expected behavior**
Bot joins channel and plays music, or throws any error

**Additional context**
I resolved this issue, by editing `src/Discord/Voice/VoiceClient.php`:
![image](https://user-images.githubusercontent.com/25950627/202299547-5e3e5021-a556-4742-8bfb-a23572bc3639.png)
to:
![image](https://user-images.githubusercontent.com/25950627/202299626-ad56eed8-313b-4317-a0c2-6da750a6153a.png)

Maybe it will help somebody. I spent 3 days on this(and lost some hair also). Maybe You can fix this in next release ;)

Peace!

**Comment by key2peace** [comment]
playRawStream expects as the name says a RAW pcm stream, not an icecast encoded aac/mp3 stream. I've made a small modification in #986 to have playFile accept urls, as files, then your solution should be like this:

```php
$discord->joinVoiceChannel($channel)->then(function (VoiceClient $client) {
  $client->playFile('http://noisefm.ru:8000/play?icy=http')->then(function () {
    echo "done\n";
  }, function ($e) {
    echo "failed to play song:\n";
  });
}, function ($e) {
  echo "failed to join voice channel:\n";
});
```
