### ISSUE TITLE
How do I delete slash command?

### ISSUE THREAD

**Issue by yoraze** [discord-php/DiscordPHP#988]
I just created `test` command with example from #691, but I dont know how to remove it now.
I tried this (actually I just replaced `save` with `delete` that I found in AbstractRepository class):
```php
$command = new Command($this->bot, [
    'name' => 'test',
    'description' => 'asdfghj',
    'type' => Command::CHAT_INPUT
]);
$this->bot->application->commands->delete($command);
```
And this isnt working so idk is there a way to remove this command?

**Comment by key2peace** [comment]
you need to obtain the $command->id you received upon save() in order to delete($command->id), if you don't have it, use $this->bot->application->commands->freshen()->then(function ($commands) { }); and loop through them to find it.

**Comment by yoraze** [comment]
This worked, thanks! ❤️
