### ISSUE TITLE
bot check

### ISSUE THREAD

**Issue by ocvcoin** [discord-php/DiscordPHP#991]
Hi
I have a problem.
For some reason I can't understand, var_dump rarely shows true for the same user & same command. Why could this happen?

PHP 7.4.3 
discord-php v7.3.3

```
$discord->listenCommand('ocv', function (Interaction $interaction) {
	
		

		//target_userid is bot??
		var_dump (  (@$interaction->data ->resolved ->users[$target_userid]->bot !== NULL)  );
		
		
    
});
```

**Comment by key2peace** [comment]
please don't use the ``Bug`` label, it is meant for bugs in DiscordPHP not in your code.
also, bot is bool, so either ``true`` or ``false`` and also you need to remove the spaces

**Comment by SQKo** [comment]
`bot` is always `true` when `target_id` is a bot, otherwise it's sometimes `null` or `false`, depends on the users cache.

**Comment by ocvcoin** [comment]
Thank you. It's clarified.
