### ISSUE TITLE
[Question] How can I send a message to the user's private message after he has joined the server?

### ISSUE THREAD

**Issue by markeze207** [discord-php/DiscordPHP#994]
How can I send a message to the user's private message after he has joined the server?
`$ds->on(Event::GUILD_MEMBER_ADD, function (Message $msg, Member $member, Discord $ds) {
        $msg->author->sendMessage('dasdas');
    });`

**Comment by key2peace** [comment]
close...
`$ds->on(Event::GUILD_MEMBER_ADD, function (Member $member) { $member->user->sendMessage('dasdas'); });`
